-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 29bf11d13689a0a9a895c41eb3591c7e942d377d
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: 2cab1949dd83734b23dc273e9c5e52a8981cab53
    hooks:
    -   id: apiary-validation
