-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 29bf11d13689a0a9a895c41eb3591c7e942d377d
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: df41a9c73edd94549cd936217a509cfa85ecdc52
    hooks:
    -   id: apiary-validation
