-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: f82fb149af2c1b552b50e3e38e38ed3a44d4cda1
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: a2922ad53cc6bd16e34287f129f5e48cf917ecb0
    hooks:
    -   id: apiary-validation
