-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 29bf11d13689a0a9a895c41eb3591c7e942d377d
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: df307147cb49900d8db4b79472ecd2324bae265a
    hooks:
    -   id: apiary-validation
