-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: f82fb149af2c1b552b50e3e38e38ed3a44d4cda1
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: f9c0c625d0b1048ef538078e6e1b7a7efa33e755
    hooks:
    -   id: apiary-validation
