-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: 5b4d7524c10dcf029dca5b2c9c43c3fbcd5dc1a4
    hooks:
    -   id: apiary-validation
