-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 003e43251aea1da33f2072f2365ec8b9ceaae070
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/benjamin99Tsai/pre-commit-apiary.git
    sha: 44ff7dcf43b37bc4931843624e72cc1b0efbae68
    hooks:
    -   id: apiary-validation
