# Group 候床、配床 waitBed
## 6/12 - 候床 [/patients/{charNo}/waitBed{?wards,priority,wardClass}]
### 取得候床資訊[GET]

+ Response 200 (application/json)

        {
            "content": {
                "wards": [
                    {
                        "title" : "加護病房",
                        "division" : [
                            {
                                "displayName" : "內科ICU",
                                "divisionCode": "MED_ICU",
                                "isChecked": true //是否已排候床，為 true 時回傳[optional]
                            },
                            ...
                        ]
                    },
                    ...
                ],
                "priority" : {
                    "preset" : "priorityA", //預設選項
                    "option": [
                        {
                            "displayName": "A",
                            "priorityCode": "priorityA"
                        },
                        ...
                    ]
                },
                "wardClass": {
                    "preset": [
                        "single",
                        ...
                    ],
                    "option": [
                        {
                            "displayName" : "1人房",
                            "wardClassCode" : "single"
                        },
                        ...
                    ]
                }

            }
        }


### 回傳候床資訊[POST]

+ Parameters
    + wards (array[string])    ... 病房
    + priority (string)   ... 候床優先順序
    + wardClass (array[string], optional) ... 床等

+ Request WaitBedInfo (application/json)

        {
            "content": {
                "wards": [
                    "MED_ICU",
                    ...
                ],
                "priority": "priorityA",
                "wardClass": [          // 後床級別排序, 依照優先順序編排
                    "single",
                    "double",
                    ...
                ]
            },
            "sessionKey": "DD07A0AF4E9F426C838185D8DD19EFE2"
        }

+ Response 200 (application/json)

        {
            "success" : true
        }

## 7/6 - 可配床細分科 [/assignBed/department]
### 取得此醫師可配床細分科清單[GET]


+ Response 200 (application/json)

        {
            "content" : [   //病房資訊陣列
                {   //病房資訊
                    "hospCode" : "T0",      //醫院代碼[string]
                    "deptCode" : "14C",    //科別代碼[string]
                    "displayName" : "胸腔內科 14C"  //顯示名稱[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number]
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50  //此次Query總筆數[number]
        }



## 7/6 - 待配床清單 [/assignBed/list{?sessionkey,departmentCode,chartNo}]
### 取得待配床病患清單[GET]

+ Parameters
    + departmentCode (string) ... 科別代碼
    + chartNo (string)  ... 病患病例號

+ Response 200 (application/json)

        {
            "content" : [   //病患資訊陣列
                {   //病患資訊
                    "patName" : "王小明",                          //病患姓名[string]
                    "patSexCode" : "M",                         //性別[string]（男性："M";女性："F"）
                    "patBirthday" : 1406938026,                 //出生日期[number(timestamp)]
                    "chartNo" : "12345678",                     //病歷號[string]
                    "priority": "Ａ",                            //優先順序[string]
                    "waitStartDate": 1416938026,                //候床起始時間 [number(timestamp)]
                    "waitEndDate": 1416938326,                  //候床結束時間 [number(timestamp), optional] 若無則不用回傳
                    "source" : "轉",                             //來源[string]
                    "hospital" : "總院",                          //原院[string]
                    "department" : "腫瘤",                        //原科[string]
                    "note" : "註記",                              //註[string]
                    "departmentName": "內科",                     //[string, optional] 科別名稱，在病患收尋清單的時候才需回傳
                    "waitBedNo": "1408992"                      //[string, optional] 候床代號
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number]
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50  //此次Query總筆數[number]
        }

## 9/22 - 病患配床資訊 [/assignBed/patients/{chartNo}{?waitBedNo,bedCode,date,originDept,bedClassCode,isolationReasonCode,isolationReasonFreeText}]
### 取得病患配床資訊[GET]

+ Parameters

   + chartNo (string)    ... 病歷號

+ Response 200 (application/json)

        {
           "content" : {   //病患資訊陣列
               "patInfo" : {   //病患資訊
                   "patName" : "王小明",                    //病患姓名[string]
                   "patSexCode" : "M",                     //性別[string]（男性："M";女性："F"）
                   "patBirthday" : 1406938026,             //出生日期[number(timestamp)]
                   "personID" : "A123456789",      //身分證號[string]
                   "chartNo" : "12345678",                 //病歷號[string]
                   "TEL" : "02-123456",                //聯絡電話[string]
                   "mobile" : "0972111222"        //手機[string]
               },
               "waitBedNo" : "1080922",   //候床單號[string]
               "waitBedInfo" : [ //候床資訊(除診療行為)
                  {
                     "title" : "候床單號",
                     "content" : "1080922"
                  },
                  ...
               ],
               "treatment" : {   //診療行為
                  "category" : "一般住院",  //類別[string]
                  "item" : "一般住院",   //項目[string]
                  "treatmentCode" : "L000001", //診療代碼[string]
                  "insurance" : "健保"   //保險別[string]
               },
               "wards" : [ //床位
                  {
                     "wardTitle" : "內科部 03A2",
                     "beds": {
                           "bedNo" : "01-01",
                           "bedClass" : "雙人",
                           "outDate" : 1406938026,      // [optional] 如果沒有指定時間就不用回傳
                           "bedCode" : "03A2-01-01",
                           "bedStatus" : "empty",       //床狀態[string](空床：“empty”;住院中，無人預定:"occupied";住院中，後有預定:"nonAvailable";預定出院:"available")
                           "isolation" : [  //是否可轉換為隔離床，UI上需另外顯示一個選單讓使用者選擇[array]
                                {
                                    "displayName" : "一般隔離",
                                    "bedClassCode" : "general"
                                },
                                {
                                    "displayName" : "負壓隔離",
                                    "bedClassCode" : "neg"
                                },
                                ...
                           ]
                     }
                  },
                  ...
               ]
           },
           "limit" : 50, //最大回傳筆數[number]
           "offset" : 0, //回傳資料偏移數[number]
           "total" : 50  //此次Query總筆數[number]
        }

### 回傳病患配床資訊[POST]

+ Parameters

   + chartNo (string)   ... 病歷號
   + waitBedNo (string) ... 候床單號
   + bedCode (string)   ... 床位代碼
   + date (string)      ... 預定日期(格式為YYYYMMDD)
   + bedClassCode   (string, optional)  ... 床等，非選擇床等則不回傳
   + isolationReasonCode (string, optional) ... 隔離原因代碼，非隔離則不回傳
   + isolationReasonFreeText (string, optional) ... 使用者選填隔離原因，隔離原因非選其他則不回傳
   + originDept (string, optional)   ... 借床原始科別，非借床則不回傳


+ Request RegisterBed (application/json)

        {
            "content": {
                "waitBedNo": "123456",
                "bedCode": "03A2-01-01",
                "date": "20151103",
                "bedClassCode" : "general",
                "isolationReasonCode" : "R1",
                "isolationReasonFreeText" : "我不想隔離",        // [string, optional] 當回傳的 isolationReasonCode 所對應的選項 textInput=true 時，就會回傳使用者輸入的文字內容
                "originDept": "MED_ICU"                         // [optional] 借床原始科別，非借床則不回傳
            },
            "sessionKey": "DD07A0AF4E9F426C838185D8DD19EFE2"
        }

+ Response 200 (application/json)

        {
            "success": true
        }

## 9/22 - 隔離床等所搭配的隔離原因 [/assignBed/isolationReason/{isolationCode}]
### 取得隔離床等所搭配的隔離原因[GET]

+ Parameters

   + isolationCode (string)   ... 隔離床等代碼

+ Response 200 (application/json)

        {
            "content" : [
                {
                    "displayName" : "隔離原因一",
                    "isolationReasonCode" : "r1"
                },
                {
                    "displayName" : "隔離原因一",
                    "isolationReasonCode" : "e2"
                },
                {
                    "displayName" : "其他",
                    "isolationReasonCode" : "other",
                    "textInput": true                       //當此選項有附帶欄位可讓使用者填入值時回傳 true，未回傳此參數時，預設為 false[boolean, optional]
                }
                ...
            ],
            "limit" : 50, //最大回傳筆數[number]
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50  //此次Query總筆數[number]

        }

## 8/4 - 醫師可指定之病患配床原始科別資訊 [/assignBed/originDept]
### 取得醫師可指定之病患配床原始科別資訊[GET]

+ Response 200 (application/json)

        {
             "content" : [   //原始科別資訊
                {   //原始科別資訊
                    "displayName" : "內科部",  //顯示名稱[string]
                    "children" : [   //次分科
                        {
                            "deptCode" : "MED",    //科別代碼[string]
                            "displayName" : "內科"  //顯示名稱[string]
                        },
                        {
                            "deptCode" : "CARD",    //科別代碼[string]
                            "displayName" : "心臟內科"  //顯示名稱[string]
                        },
                        ...
                    ]
                },
                ...
             ],
             "limit" : 50, //最大回傳筆數[number]
             "offset" : 0, //回傳資料偏移數[number]
             "total" : 50  //此次Query總筆數[number]
        }
