# Group 候床、配床 waitBed
## 6/12 - 候床 [/patients/{charNo}/waitBed{?wards,piority,wardClass}]
### 取得候床資訊[GET]

+ Response 200 (application/json)

        {
            "content": {
                "wards": [
                    {
                        "title" : "加護病房",
                        "division" : [
                            {
                                "displayName" : "內科ICU",
                                "divisionCode": "MED_ICU",
                                "isChecked": true //是否已排候床，為 true 時回傳[optional]
                            },
                            ...
                        ]
                    },
                    ...
                ],
                "piority" : {
                    "default" : "piorityA", //預設選項
                    "option": [
                        {
                            "displayName": "A",
                            "piorityCode": "piorityA"
                        },
                        ...
                    ]
                },
                "wardClass": {
                    "default": [
                        "single",
                        ...
                    ],
                    "option": [
                        {
                            "displayName" : "1人房",
                            "wardClassCode" : "single"
                        },
                        ...
                    ]
                }

            }
        }


### 回傳候床資訊[POST]

+ Parameters

    + wards (array[string])    ... 病房
    + piority (string)   ... 候床優先順序
    + wardClass (array[string], optional) ... 床等

+ Response 200 (application/json)

        {
            "success" : true,
            "content" : {

            }
        }

## 7/6 - 可配床細分科 [/asignBed/department]
### 取得此醫師可配床細分科清單[GET]


+ Response 200 (application/json)

        {
            "content" : [   //病房資訊陣列
                {   //病房資訊
                    "hospCode" : "T0",      //醫院代碼[string]
                    "deptCode" : "14C",    //科別代碼[string]
                    "displayName" : "胸腔內科 14C"  //顯示名稱[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number]
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50  //此次Query總筆數[number]
        }



## 7/6 - 待配床清單 [/asignBed/department/{deptCode}]
### 回傳待配床病患清單[GET]

+ Parameters

    + deptCode (string)    ... 科別代碼

+ Response 200 (application/json)

        {
            "content" : [   //病患資訊陣列
                {   //病患資訊
                    "patName" : "王小明",                    //病患姓名[string]
                    "patSexCode" : "M",                     //性別[string]（男性："M";女性："F"）
                    "patBirthday" : 1406938026,             //出生日期[number(timestamp)]
                    "chartNo" : "12345678",                 //病歷號[string]
                    "piority" : "Ａ",                        //優先順序[string]
                    "waitStartDate": 1416938026,              //候床起始時間 [number(timestamp)]
                    "waitEndDate": 1416938326,                //候床結束時間 [number(timestamp), optional] 若無則不用回傳
                    "source" : "轉",                         //來源[string]
                    "hospital" : "總院",                      //原院[string]
                    "department" : "腫瘤",                    //原科[string]
                    "note" : "註記"                           //註[string]
                },
                ...
            ],
            "limit" : 50, //最大回傳筆數[number]
            "offset" : 0, //回傳資料偏移數[number]
            "total" : 50  //此次Query總筆數[number]
        }
