# Group Blood Order

## 血品相關病患資訊 [/patients/{chartNo}/bloodInfo{?sessionKey}]
### 取得病患血品相關資訊 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": {
                "bloodType": "type_unknown",                                    // [string] 檢驗血型
                "specimenInfo": "檢體: -- 採檢: -- 提血期限: 採檢後 3 日內",          // [string] 有效檢體
                "inspectInfo": "HB 12.0 (20150520-RL)  PLT 472 (20150520-RL)",  // [string] 檢驗資訊
                "dictateBloodType": {                                           // 口述血型
                    "type": "type_unknown",                                     // [string] 血型代號
                    "description": "自過敏史取得口述血型, 資料來源為舊病歷資料"         // [string] 口述血型敘述
                },
                "newbornInfoRequired": false                                    // [boolean] 是否需要額外輸入新生兒資料
            }
        }

## 血品清單 [/bloodOrder/bloodTypes{?sessionKey,displayAll}]
### 取得血品清單 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey
    + displayAll        (string) ... 是否顯示完整清單 true/false 若為 false 則回傳常用血品即可

+ Response 200 (application/json)


        {
            "content": {
                "groups": [
                    {
                        "title": "紅血球血品",                          // [string] 血品群組名稱
                        "items": [                                    // 血品清單
                            {
                                "code":     "000PP011",               // [string] 血品代碼
                                "name":     "Packed RBC",             // [string] 血品名稱
                                "unit":     "U",                      // [string] 血品單位
                                "frqUsed":  true                      // [boolean] 是否常用
                            },
                            {
                                "code":     "000PP141",               // [string] 血品代碼
                                "name":     "Leukocyte-Poor RBC",     // [string] 血品名稱
                                "unit":     "U",                      // [string] 血品單位
                                "frqUsed":  true                      // [boolean] 是否常用
                            },
                            ...
                        ],
                        "adaptations": [    // 輸血適應症清單
                            {
                                "title": "開刀前或侵襲術式前備血",        // [string] 該選項所顯示的標題
                                "return_value": "RBC_001"             // [string] 該選項選取時的回傳值
                            },
                            {
                                "title": "大量輸血",                    // [string] 該選項所顯示的標題
                                "return_value": "RBC_002"             // [string] 該選項選起時的回傳值
                            },
                            ...
                        ],
                        "notification": {  // [optional] 額外提示，當沒有時不用回傳
                            "title": "指定血小板血品供應不足時",
                            "content": "本血品庫存不足時, 相同血型血品不足時, 血庫將電話通知給與優先替代血型, 指定種類不足時, 將電話連繫醫師替代並重開醫令"
                        }
                    },
                    ...
                ]
            }
        }

## 血品備血醫囑 [/account/{accountNo}/bloodOrderSheets{?sessionKey}]
### 取得備血醫囑清單 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": [
                {
                    "sheetNo": "2004681",                               // [string] 備血單號
                    "blood": {                                          // 血品相關資訊
                        "name": "Packed RBC",                           // [string] 血品名稱
                        "unit": "U"                                     // [string] 血品單位
                    },
                    "totalAmount": 6,                                   // [number] 總備血量
                    "issuedAmount": 3,                                  // [number] 已開血量
                    "issueOrders": [                                    // 輸血醫囑清單 [optional] 若無則不用回傳
                        {
                            "issueNo": "2004681-01",                    // [string] 提血單號
                            "amount": 3,                                // [number] 提血血量
                            "status": "(待血庫接單)(醫囑未確認)"           // [string] 提血單狀態描述
                        },
                        ...
                    ],
                    "creatorNo": "111291",                              // [string] 開立醫師員編
                    "creatorName": "王大明",                             // [string] 開立醫師姓名
                    "createdTime": 1436256491,                          // [number(timestamp)] 開立時間
                    "expectedIssueDay": 1436260091,                     // [number(timestamp)] 預計輸血日期
                    "verified": false,                                  // [boolean] 醫囑是否被確認
                    "additionalInfo": [
                        {
                            "title": "用血時機",
                            "content": "先行備血, 分批輸血, 由護理師啟動提血"
                        },
                        {
                            "title": "備血血品狀態",
                            "content": "待血庫接單(醫囑未確認)"
                        }
                    ]
                }
            ]
        }

### 開立備血醫囑 [POST]

+ Request IssueBloodOrderSheets (application/json)

        {
            "content": {
                "dictateBloodType": "type_0",                           // [string] 口述血型代碼
                "newBornInfo": {                                        // [optional] 新生兒資料，若不需要填寫不會傳入
                    "motherBloodType": "type_A",                        // [string] 母親口述血型
                    "fatherBloodType": "type_unknown",                  // [string] 父親口述血型
                    "hadTransfused": "T",                               // [string] 使否曾經輸血 T:為是 F:為否 U:不清楚
                    "hadExchanged": "U",                                // [string] 使否曾經換血 T:為是 F:為否 U:不清楚
                    "needPedipack": false                               // [boolean] 是否需要分裝血品
                },
                "code": "000PP011",                                     // [string] 欲開立之血品代碼
                "amount": 2,                                            // [number] 開立血品之數量
                "adaptation": "RBC_001",                                // [string] 開立血品之適應症代碼
                "destination": {                                        // 送達地點
                    "code": "T01",                                      // [string] 送達地點代號
                    "description": "11B-07-01"                          // [string] 送達地點資訊
                },
                "transfuseTime": {                                      // 輸血時機
                    "code": "BeforSurgery",                             // [string] 輸血時機代碼
                    "Operation": "OPERATION_TYPE",                      // [string, optional] 術式說明 手術/處置前備血用
                    "date": 1435744800,                                 // [number(timestamp), optional] 日期 手術/處置前備血用
                    "description": "DESCRIPTION_CONTENT"                // [string] 其他描述
                },
                "flowSpeed": {                                          // 輸血流速
                    "code": "01",                                       // [string] 流速代碼
                    "description": "DESCRIPTION_CONTENT"                // [string] 其他說明
                },
                "notification": "NOTIFICATION_CONTENT"                  // [string] 其他敘述
            },
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"            // [string] SessionKey
        }

+ Response 201 (application/json)


        {
            "success": true,
            "content": {
                "sheetNo": "2004681"                                    // [string]  備血醫囑單號
            }
        }


## 血品輸血醫囑清單 [/accont/{accountNo}/boodIssueOrders{?sessionKey,amount,expectedIssueDay,destCode,destDescription}]
### 開立輸血醫囑 [POST]
+ Parameters
    + sessionKey        (string) ... SessionKey
    + amount            (number) ... 提血數量
    + expectedIssueDay  (number) ... 預計輸血日期 unix timestamp 格式
    + destCode          (string) ... 送達地點代碼
    + destDescription   (string, optional) ... 送達地點敘述

+ Response 201 (application/json)

        {
            "success": true,
            "content": {
                "issueNo": "2004681-1"
            }
        }

## 血品輸血醫囑 [/account/{accountNo}/bloodIssueOrder/{issueNo}{?sessionKey}]
### 取得輸血醫囑內容 [GET]

+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": {
                "issueNo": "2004681-1",                             // [string] 輸血醫囑單號
                "blood": {                                          // 血品相關資訊
                    "name": "Packed RBC",                           // [string] 血品名稱
                    "unit": "U"                                     // [string] 血品單位
                },
                "status": "待血庫接單 (醫囑未確認)",                   // [string] 狀態描述
                "amount": 2,                                        // [number] 數量
                "verified": false,                                  // [boolean] 是否被確認
                "additionalInfo": [
                    {
                        "title": "送達地",
                        "content": "病房 0PII-06-03"
                    },
                    {
                        "title": "表單申請",
                        "content": "XXX (簡碼: 99999) 2015/07/07"
                    }
                    ...
                ]
            }
        }
