# Group Blood Order

## 血品相關病患資訊 [/patients/{chartNo}/bloodInfo{?sessionKey}]
### 取得病患血品相關資訊 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": {
                "bloodTypeInfo": {                                              // 檢驗血型資料
                    "description": "此病人無檢驗血型資料",                         // [string] 血型資料內容
                    "hilight": true                                             // [boolean] 是否要 highlight資訊內容
                },
                "specimenInfo": "檢體: -- 採檢: -- 提血期限: 採檢後 3 日內",         // 有效檢體資訊
                "inspectInfo": [                                                // 檢驗資訊
                    {
                        "title": "HB",
                        "value": 12.0,                                          // [number] 檢驗數值
                        "description": "(20150520-RL)"                          // [string] 檢驗描述
                    },
                    {
                        "title": "PLT",
                        "value": 472,                                           // [number] 檢驗數值
                        "description": "(20150520-RL)"                          // [string] 檢驗描述
                    },
                    {
                        "title": "PT",
                        "value": 12.0,                                          // [number] 檢驗數值
                        "description": "(20150520-CT)"                          // [string] 檢驗描述
                    },
                    {
                        "title": "PTT",
                        "value": 36.4,                                          // [number] 檢驗數值
                        "description": "(20150521-RL)"                          // [string] 檢驗描述
                    }
                ],
                "dictateBloodType": {                                           // 口述血型
                    "type": "type_unknown",                                     // [string] 血型代號
                    "description": "自過敏史取得口述血型, 資料來源為舊病歷資料"         // [string] 口述血型敘述
                },
                "newbornInfo": {                                                // [optional] 若無則不用回傳
                    "motherBloodType": "type_A",                                // [string] 母親口述血型
                    "fatherBloodType": "type_unknown",                          // [string] 父親口述血型
                    "hadTransfused": "T",                                       // [string] 使否曾經輸血 T:為是 F:為否 U:不清楚
                    "transfuseInfo": {                                          // [optional] 只有曾經輸血有記錄才回傳
                        "blood": "Packed RBC",                                  // [string] 血品
                        "bloodType": "type_A"                                   // [string] 血型
                    },
                    "hadExchanged": "T",                                        // [string] 使否曾經換血 T:為是 F:為否 U:不清楚
                    "exchangeInfo": {                                           // [optional] 只有曾經換血有記錄才回傳
                        "blood": "Packed RBC",                                  // [string] 血品
                        "bloodType": "type_A"                                   // [string] 血型
                    },
                    "needPedipack": false                                       // [boolean] 是否需要分裝血品
                }
            }
        }

## 血品清單 [/bloodOrder/bloods{?sessionKey,hospitalCode,displayAll}]
### 取得血品清單 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey
    + hospitalCode      (string) ... 院區碼
    + displayAll        (string) ... 是否顯示完整清單 true/false 若為 false 則回傳常用血品 即 freqUsed=True 之血品即可

+ Response 200 (application/json)


        {
            "content": {
                "groups": [
                    {
                        "title": "紅血球血品",                                    // [string] 血品群組名稱
                        "items": [                                              // 血品清單
                            {
                                "code":     "000PP011",                         // [string] 血品代碼
                                "title":    "Packed RBC",                       // [string] 血品顯示名稱
                                "unit":     "U",                                // [string] 血品單位
                                "frqUsed":  true,                               // [boolean] 是否常用
                                "note": [                                       // [optional] 備註欄位需要元件 若無則不用回傳
                                    {
                                        "title": "使用新鮮血",                    // [string] 顯示標題
                                        "returnKey": "c_use_fresh_blood",       // [string] 回傳結果時該元件所對應的鍵值
                                        "type": "C",                            // [string] 問題種類，如日期為 D，checkbox 為 C
                                        "required": true                        // [boolean] 問題是否為必填項目
                                    },
                                    ...
                                ]
                            },
                            {
                                "code":     "000PP141",                         // [string] 血品代碼
                                "title":    "Leukocyte-Poor RBC",               // [string] 血品顯示名稱
                                "unit":     "U",                                // [string] 血品單位
                                "frqUsed":  true                                // [boolean] 是否常用
                            },
                            ...
                        ],
                        "adaptations": [    // 輸血適應症清單
                            {
                                "title": "開刀前或侵襲術式前備血",                  // [string] 該選項所顯示的標題
                                "code": "RBC_001"                               // [string] 該選項選取時回傳用的適應症代碼
                            },
                            {
                                "title": "大量輸血",                              // [string] 該選項所顯示的標題
                                "code": "RBC_002"                               // [string] 該選項選取時回傳用的適應症代碼
                            },
                            ...
                        ],
                        "notification": {  // [optional] 額外提示，當沒有時不用回傳
                            "title": "指定血小板血品供應不足時",
                            "content": "本血品庫存不足時, 相同血型血品不足時, 血庫將電話通知給與優先替代血型, 指定種類不足時, 將電話連繫醫師替代並重開醫令"
                        }
                    },
                    ...
                ]
            }
        }

## 血品備血醫囑 [/account/{accountNo}/blood/prepareOrders{?sessionKey}]
### 取得備血醫囑清單 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": [
                {
                    "orderRecordId": "2004681",                                 // [string] 備血醫囑對應之 unique ID
                    "bloods": [                                                 // 血品相關資訊
                        {
                            "name": "Packed RBC",                               // [string] 血品名稱
                            "unit": "U",                                        // [string] 血品單位
                            "totalAmount": 6,                                   // [number] 總備血量
                            "issuedAmount": 3,                                  // [number] 已開血量
                            "transfusionOrders": [                              // 輸血醫囑清單 [optional] 若無則不用回傳
                                {
                                    "orderRecordId": "2004681-01",              // [string] 輸血醫囑之 unique ID
                                    "amount": 3,                                // [number] 輸血血量
                                    "status": "(待血庫接單)(醫囑未確認)"            // [string] 狀態描述
                                },
                                ...
                            ]
                        },
                        ...
                    ],
                    "creatorNo": "111291",                                      // [string] 開立醫師員編
                    "creatorName": "王大明",                                     // [string] 開立醫師姓名
                    "createdTime": 1436256491,                                  // [number(timestamp)] 開立時間
                    "expectedIssueDay": 1436260091,                             // [number(timestamp)] 預計輸血日期
                    "verified": false,                                          // [boolean] 醫囑是否被確認
                    "additionalInfo": [                                         // [optional] 額外資訊 若無則不用回傳
                        {
                            "title": "用血時機",
                            "content": "先行備血, 分批輸血, 由護理師啟動提血"
                        },
                        {
                            "title": "備血血品狀態",
                            "content": "待血庫接單(醫囑未確認)"
                        }
                    ]
                },
                ...
            ]
        }

### 開立備血醫囑 [POST]

+ Request IssueBloodOrderSheets (application/json)

        {
            "content": {
                "dictateBloodType": "type_0",                                   // [string] 口述血型代碼
                "newbornInfo": {                                                // [optional] 新生兒資料，若不需要填寫不會傳入
                    "motherBloodType": "type_A",                                // [string] 母親口述血型
                    "fatherBloodType": "type_unknown",                          // [string] 父親口述血型
                    "hadTransfused": "T",                                       // [string] 使否曾經輸血 T:為是 F:為否 U:不清楚
                    "hadExchanged": "U",                                        // [string] 使否曾經換血 T:為是 F:為否 U:不清楚
                    "needPedipack": false                                       // [boolean] 是否需要分裝血品
                },
                "bloodTypes": [                                                 // 血品資訊
                    {
                        "code": "000PP011",                                     // [string] 欲開立之血品代碼
                        "amount": 2,                                            // [number] 開立血品之數量
                        "adaptation": "RBC_001",                                // [string] 開立血品之適應症代碼
                        "destination": {                                        // 送達地點
                            "code": "T01",                                      // [string] 送達地點代號
                            "description": "11B-07-01"                          // [string] 送達地點資訊
                        },
                        "transfuseTime": {                                      // 輸血時機
                            "code": "BeforSurgery",                             // [string] 輸血時機代碼
                            "Operation": "OPERATION_TYPE",                      // [string, optional] 術式說明 手術/處置前備血用
                            "date": 1435744800,                                 // [number(timestamp), optional] 日期 手術/處置前備血用
                            "description": "DESCRIPTION_CONTENT"                // [string] 其他描述
                        },
                        "flowSpeed": {                                          // 輸血流速
                            "code": "01",                                       // [string] 流速代碼
                            "description": "DESCRIPTION_CONTENT"                // [string] 其他說明
                        },
                        "notification": "NOTIFICATION_CONTENT"                  // [string] 其他敘述
                    },
                    ...
                ]
            },
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"                    // [string] SessionKey
        }

+ Response 201 (application/json)


        {
            "success": true,
            "content": {
                "orderRecordId": "2004681"                                      // [string]  備血醫囑單號
            }
        }


## 血品輸血醫囑清單 [/account/{accountNo}/blood/transfusionOrders{?sessionKey,amount,expectedIssueDay,destCode,destDescription,prepareOrderId}]
### 開立輸血醫囑 [POST]
+ Parameters
    + sessionKey        (string) ... SessionKey
    + prepareOrderId    (string) ... 對應的備血醫囑 ID
    + amount            (number) ... 提血數量
    + expectedIssueDay  (number) ... 預計輸血日期 unix timestamp 格式
    + destCode          (string) ... 送達地點代碼
    + destDescription   (string, optional) ... 送達地點敘述


+ Request IssueTranfusionOrder (application/json)

            {
                "content": {
                    "prepareOrderId": "xxx_001",
                    "amount": 10,
                    "expectedIssueDay": 1438250400,
                    "destCode": "12C",
                    "destDescription": "the additional description"     // [optional] 如果沒有需要填寫就不會上傳
                },
                "sessionKey": "DD07A0AF4E9F426C838185D8DD19EFE2"
            }


+ Response 201 (application/json)

        {
            "success": true,
            "content": {
                "orderRecordId": "2004681-1"
            }
        }

## 血品輸血醫囑 [/account/{accountNo}/transfusionOrders/{orderRecordId}{?sessionKey}]
### 取得輸血醫囑內容 [GET]

+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": {
                "orderRecordId": "2004681-1",                                   // [string] 輸血醫囑 ID
                "blood": {                                                      // 血品相關資訊
                    "name": "Packed RBC",                                       // [string] 血品名稱
                    "unit": "U"                                                 // [string] 血品單位
                },
                "status": "待血庫接單 (醫囑未確認)",                                // [string] 狀態描述
                "amount": 2,                                                    // [number] 數量
                "verified": false,                                              // [boolean] 是否被確認
                "additionalInfo": [
                    {
                        "title": "送達地",
                        "content": "病房 0PII-06-03"
                    },
                    {
                        "title": "表單申請",
                        "content": "XXX (簡碼: 99999) 2015/07/07"
                    }
                    ...
                ]
            }
        }
