# Group 急救紀錄 ERRecrod
## 8/10 - 急救紀錄事件按鈕 [/ERRecord/Layout]
### 取得急救紀錄事件按鈕 [GET]

+ Response 200 (application/json)

        {
            "example": [
                {
                    "category": "S",    //類別代碼 [string]
                    "displayName": "STATUS",    //類別顯示名稱 [string]
                    "displayNameTC": "狀態評估",    //類別顯示名稱(中文) [string]
                    "buttons": [    //類別含有的按鈕
                        {   //button
                            "buttonCode": "SCON",   //按鈕代碼  [string]
                            "displayName": "Consciousness", //按鈕顯示名稱 [string]
                            "displayNameTC": "意識評估",    //按鈕顯示名稱(中文) [string]
                            "count" : true, //此按鈕需要被計數 [boolean, optional]
                            "default": {    //點擊預設紀錄事件，無此Key表示無預設紀錄，有Key無內容表示依第一次使用者所選紀錄為預設記錄   [optional]
                                "itemCode": "SCON1U",
                                "displayName": "U",
                                "displayNameTC": "U",
                                "recordNote": "意識評估:否"
                            },
                            "child": {  //下層選項  [optional]
                                "type": "records",  //可以是 records 或 buttons
                                "content": [
                                    {   //每一個record Object，皆會產生一筆紀錄，紀錄欄位為time[timestamp]、itemCode、recordNote、text(使用者輸入值)，當無參數 require = false 時，所有選項與欄位皆為必填。
                                        "type": "option",
                                        "content": [
                                            {
                                                "itemCode": "SCON1A",
                                                "displayName": "A",
                                                "displayNameTC": "A",
                                                "recordNote": "意識評估:清"
                                            },
                                            {
                                                "itemCode": "SCON1V",
                                                "displayName": "V",
                                                "displayNameTC": "V",
                                                "recordNote": "意識評估:聲"
                                            },
                                            {
                                                "itemCode": "SCON1O",
                                                "displayName": "Other",
                                                "displayNameTC": "其他",
                                                "textInput": true,  //當此參數為 true 時，表示有textfield可讓使用者填入值。[boolean, optional]
                                                "number" : true,    //當此參數為 true 時，表示此欄位只能填入數值 [boolean, optional]
                                                "recordNote": "意識評估:[\1]"   //如使用者填入值為 2 ，recordNote 將紀錄為 意識評估：2
                                            }
                                        ]
                                    }
                                ]
                            }
                        },
                        {
                            "buttonCode": "SCON2",
                            "displayName": "COMA SCALE",
                            "displayNameTC": "昏迷指數",
                            "child": {  //下層選項  [optional]
                                "type": "records",
                                "content": [
                                    {
                                        "type": "textfield",
                                        "itemCode": "SCON2E",
                                        "displayName": "E:",
                                        "displayNameTC": "E:",
                                        "default": "1", //預設數值 [string. optional]
                                        "number": true, //值是否只能填入數值 [string. optional]
                                        "recordNote": "昏迷指數:E [\1]"
                                    },
                                    {
                                        "type": "textfield",
                                        "itemCode": "SCON2M",
                                        "displayName": "M:",
                                        "displayNameTC": "M:",
                                        "default": "1", //預設數值 [string. optional]
                                        "number": true, //值是否只能填入數值 [string. optional]
                                        "recordNote": "昏迷指數:M [\1]"
                                    },
                                    {
                                        "type": "textfield",
                                        "itemCode": "SCON2V",
                                        "displayName": "V:",
                                        "displayNameTC": "V:",
                                        "default": "1", //預設數值 [string. optional]
                                        "number": true, //值是否只能填入數值 [string. optional]
                                        "require" : false, //當require為 false 時，使用者可選擇不填入此數值，當使用者不填入數值時，不用紀錄此項 [boolean, optional]
                                        "recordNote": "昏迷指數:V [\1]"
                                    }
                                ]
                            }
                        },
                        {
                            "buttonCode": "SCPR",
                            "displayName": "CPR QUALITY",
                            "displayNameTC": "急救品質",
                            "default": {    //點擊預設紀錄事件    [string,  optional]
                                "itemCode": "SCPRET",
                                "displayName": "EtCO2",
                                "displayNameTC": "EtCO2",
                                "textInput": true,
                                "number": true,
                                "recordNote": "ETCO2:[\1]"
                            },
                            "child": {  //下層選項  [optional]
                                "type": "records",
                                "content": [
                                    {   //每一個record Object，皆會產生一筆紀錄，紀錄欄位為time[timestamp]、itemCode、recordNote、text(使用者輸入值)
                                        "type": "option",
                                        "content": [
                                            {
                                                "itemCode": "SCPRET",
                                                "displayName": "EtCO2",
                                                "displayNameTC": "EtCO2",
                                                "textInput": true,  //當此參數為 true 時，表示有textfield可讓使用者填入值。[boolean, optional]
                                                "number" : true,    //當此參數為 true 時，表示此欄位只能填入數值 [boolean, optional]
                                                "recordNote": "ETCO2:[\1]"
                                            },
                                            {
                                                "itemCode": "SCPRPC",
                                                "displayName": "PCO2",
                                                "displayNameTC": "PCO2",
                                                "textInput": true,  //當此參數為 true 時，表示有textfield可讓使用者填入值。[boolean, optional]
                                                "number" : true,    //當此參數為 true 時，表示此欄位只能填入數值 [boolean, optional]
                                                "recordNote": "PCO2:[\1]"
                                            },
                                            {
                                                "itemCode": "SCPRPO",
                                                "displayName": "PO2",
                                                "displayNameTC": "PO2",
                                                "textInput": true,  //當此參數為 true 時，表示有textfield可讓使用者填入值。[boolean, optional]
                                                "number" : true,    //當此參數為 true 時，表示此欄位只能填入數值 [boolean, optional]
                                                "recordNote": "PO2:[\1]"
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    ]
                }
            ],
            "content": [
            ]
        }

## 9/10 - 急救紀錄邏輯 [/ERRecord/Logic]
### 取得急救紀錄邏輯 [GET]

+ Response 200 (application/json)

        {
            "example": {
                "提示": [
                    {
                        "flag": "ABC",  //當flag存在時，執行 action [string, optional]
                        "delay": 120,   //幾秒後執行 action [number, optional]
                        "repeat": 0,    //重複執行次數，0為無限次 [number, optional]
                        "interval": 200,    //重複時間間隔，以秒為單位 [number, optional]
                        "repeatCode": "ABC",    //重複事件代碼，用於停止此重複事件與判別此重複事件是否存在，當重複事件以存在時，不再次產生重複事件[string, optional]
                        "action": "highlight",
                        "buttonCode": ""    //欲提示之按鈕
                    }
                ],
                "關閉提示": [
                    {
                        "noFlag": "ABC",    //當flag不存在時，執行 action [string, optional]
                        "action": "unhighlight",
                        "buttonCode": ""
                    }
                ],
                "關閉點擊": [
                    {
                        "action": "disable",
                        "buttonCode": ""
                    }
                ],
                "count++": [    //計數事件執行次數。
                    {
                        "action": "count",
                        "itemCode": ""
                    }
                ],
                "resetCount": [ //重置事件執行次數
                    {
                        "action": "resetCount",
                        "itemCode": ""
                    }
                ],
                "播放聲音": [
                    {
                        "action": "playSound",
                        "soundCode": "chest",
                        "delay": 120
                    }
                ],
                "stopRepeat": [
                    {
                        "action": "stopRepeat",
                        "repeatCode": "ABC"
                    }
                ],
                "addFlag": [
                    {
                        "action": "addFlag",
                        "flagCode": "ABC"
                    }
                ],
                "removeFlag": [
                    {
                        "action": "removeFlag",
                        "flagCode": "ABC"
                    }
                ],
                "執行": [ //執行事件組合
                    {
                        "action": "execute",
                        "excuteCode": "_PLAYCPR"
                    }
                ],
                "ROSC": [
                    {
                        "action": "ROSC"
                    }
                ],
                "terminate": [
                    {
                        "action": "terminate"
                    }
                ]
            },
            "content": {
                "start": [  //當一開始時，需要執行的事件，事件依序執行。
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    }
                ],
                "評估呼吸": [   //當評估呼吸事件觸發時，需要執行的事件。
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    }
                ]
            }
        }
