# Group 急救紀錄 ERRecrod

## 10/15 - 急救元件內容版本更新 [/ERRecord/versions]
### 取得最新的版本號 [GET]

+ Response 200 (application/json)

        {
            "content": [
                {
                    "path": "/ERRecord/elements",       // [string] the path for the corresponding interface
                    "version": "0.0.2"                  // [string] the version tag
                },
                {
                    "path": "/ERRecord/actions",
                    "version": "0.1.0a"
                },
                ...
            ]
        }

## 9/21 - 急救紀錄事件按鈕 [/ERRecord/layout]
### 取得急救紀錄事件按鈕 [GET]

+ Response 200 (application/json)

        {
            "example": [
                {
                    "category": "S",    //類別代碼 [string]
                    "displayName": "STATUS",    //類別顯示名稱 [string]
                    "displayNameTC": "狀態評估",    //類別顯示名稱(中文) [string]
                    "items": [    //類別含有的按紐
                        {
                            "itemCode": "SCON",   //步驟(元件)代碼  [string]
                            "items": [  //下層選項  [optional]
                                {
                                    "itemCode" : "SCON1OP"
                                }
                            ]
                        },
                        {
                            "itemCode": "SCON2",
                            "items": [  //下層選項  [optional]
                                {
                                    "itemCode" : "SCON2E"
                                },
                                {
                                    "itemCode" : "SCON2M"
                                },
                                {
                                    "itemCode" : "SCON2V"
                                }
                            ]
                        }
                    ]
                }
            ],
            "content": [
            ]
        }


## 9/21 - 急救紀錄步驟 [/ERRecord/items]
### 取得急救紀錄步驟 [GET]

+ Response 200 (application/json)

        {
            "example": {
                "SCON" : {  //example for button
                    "type": "button",   //元件類別 (button, option, textfield, optionItem) [string]
                    "displayName": "Consciousness", //元件顯示名稱 [string]
                    "displayNameTC": "意識評估",    //元件顯示名稱(中文) [string]
                    "count" : true, //此元件(按鈕)需要被計數，未回傳此參數時，預設為 false [boolean, optional]
                    "isNeededSetDefault" : true,  //是否需要將使用者於此急救過程中第一次選擇的選項作為預設值，未回傳此參數時，預設為 false [boolean, optional]
                    "default" : "SCON1U"   //此按鈕有預設值時回傳 itemCode，[string, optional]
                },
                "SCON2E" : {    //example for textfield
                    "type": "textfield",   //元件類別 (button, option, textfield, optionItem) [string]
                    "displayName": "E:",    //元件顯示名稱 [string]
                    "displayNameTC": "E:",  //元件顯示名稱(中文) [string]
                    "default": "1", //預設數值，未回傳此參數時，預設為空值 [string. optional]
                    "number": true, //值是否只能填入數值，未回傳此參數時，預設為 false [string. optional]
                    "require" : false //當require為 false 時，使用者可選擇不填入此數值，當使用者不填入數值時，不用紀錄此項，未回傳此參數時，預設為 true [boolean, optional]
                },
                "SCON1OP" : {   //example for option
                    "type": "option",   //元件類別 (button, option, textfield, optionItem) [string]
                    "options" : [   //選項 (optionItem)
                        "SCON1A",
                        "SCON1V",
                        "SCON1P",
                        "SCON1U"
                    ]
                },
                "SCON1A" :{ //example for optionItem
                    "type": "optionItem",
                    "displayName": "A",
                    "displayNameTC": "A",
                    "textInput": true,  //當此選項有附帶欄位可讓使用者填入值，未回傳此參數時，預設為 false[boolean, optional]
                    "default": "1",  //預設數值 [string. optional]
                    "number" : true    //當此參數為 true 時，表示此欄位只能填入數值，未回傳此參數時，預設為 false [boolean, optional]
                }
            },
            "content": {

            }

        }


## 9/21 - 急救紀錄元件紀錄內容 [/ERRecord/record]
### 急救紀錄元件紀錄內容 [GET]

+ Response 200 (application/json)

        {
            "example": {    //每一個record Object，皆會產生一筆紀錄，紀錄欄位為time[timestamp]、itemCode、recordNote、text(使用者輸入值)，當無參數 require = false 時，所有選項與欄位皆為必填。
                "SCON2E" : "昏迷指數:E [\1]",    //當此 item 有使用者填入欄位時，使用者填入值已[\1]表示，如使用者填入值為 2 ，recordNote 將紀錄為 "昏迷指數:E 2"
                "SCON1A" : "意識評估:清"
            },
            "content": {

            }

        }


## 9/10 - 急救紀錄邏輯 [/ERRecord/logic]
### 取得急救紀錄邏輯 [GET]

+ Response 200 (application/json)

        {
            "example": {
                "提示": [
                    {
                        "flag": "ABC",  //當flag存在時，執行 action [string, optional]
                        "delay": 120,   //幾秒後執行 action [number, optional]
                        "repeat": 0,    //重複執行次數，0為無限次 [number, optional]
                        "interval": 200,    //重複時間間隔，以秒為單位 [number, optional]
                        "repeatCode": "ABC",    //重複事件代碼，用於停止此重複事件與判別此重複事件是否存在，當重複事件以存在時，不再次產生重複事件[string, optional]
                        "action": "highlight",
                        "buttonCode": ""    //欲提示之按鈕
                    }
                ],
                "關閉提示": [
                    {
                        "noFlag": "ABC",    //當flag不存在時，執行 action [string, optional]
                        "action": "unhighlight",
                        "buttonCode": ""
                    }
                ],
                "關閉點擊": [
                    {
                        "action": "disable",
                        "buttonCode": ""
                    }
                ],
                "count++": [    //計數事件執行次數。
                    {
                        "action": "count",
                        "itemCode": ""
                    }
                ],
                "resetCount": [ //重置事件執行次數
                    {
                        "action": "resetCount",
                        "itemCode": ""
                    }
                ],
                "播放聲音": [
                    {
                        "action": "playSound",
                        "soundCode": "chest",
                        "delay": 120
                    }
                ],
                "stopRepeat": [
                    {
                        "action": "stopRepeat",
                        "repeatCode": "ABC"
                    }
                ],
                "addFlag": [
                    {
                        "action": "addFlag",
                        "flagCode": "ABC"
                    }
                ],
                "removeFlag": [
                    {
                        "action": "removeFlag",
                        "flagCode": "ABC"
                    }
                ],
                "執行": [ //執行事件組合
                    {
                        "action": "execute",
                        "excuteCode": "_PLAYCPR"
                    }
                ],
                "ROSC": [
                    {
                        "action": "ROSC"
                    }
                ],
                "terminate": [
                    {
                        "action": "terminate"
                    }
                ]
            },
            "content": {
                "start": [  //當一開始時，需要執行的事件，事件依序執行。
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    }
                ],
                "評估呼吸": [   //當評估呼吸事件觸發時，需要執行的事件。
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    },
                    {
                        "action": "highlight",
                        "buttonKey": ""
                    }
                ]
            }
        }

## 10/15 - 急救記錄 [/ERRecord/record]
### 回傳急救記錄[POST]
Content-type: multipart/form-data
<br> - The first part will contain the follwing JSON content for the record info
<br> - The JSON content will be encoede with UTF-8 and than converted into binary with base64 encoded
<br> - 急救前影像: name = before
<br> - 急救後影像: name = after
<br> - 急救中影像: name = progress_%03d, 例如第三張為 progress_003


+ Request UploadRecord

        {
            "content": {
                "chartNo": "123456",    //病歷號
                "start": 1444638128,    //急救開始時間(timestamp)[number]
                "end" : 1444639128, //急救結束時間(timestamp)[number]
                "ERReason" : {
                    "commandDoctor" : "111281", //現場指揮醫師
                    "NS" : "123456",    //護理人員
                    "cardicOrigin": {   //心臟因素
                        "code": "A01,A00",              // [string]
                        "note": "xxxxx"             // [string, optional]
                    },
                    "respiratoryOrigin": {  //呼吸因素
                        "code": "B01,B00",              // [string]
                        "note": "xxxxx"             // [string, optional]
                    },
                    "neurologicalOrigin": {  //神經學因素
                        "code": "C00",              // [string]
                        "note": "xxxxx"             // [string, optional]
                    },
                    "infectionOrigin": {
                        "code": "D01"               // [string]
                    },
                    "trauma": {
                        "code": "E01"               // [string]
                    },
                    "others": {
                        "code": "F00",              // [string]
                        "note": "xxxxx"             // [string, optional]
                    }
                },
                "patientInfo": {
                    "type": 0,          // 急救記錄類別 0 for newborn, 1 for child, 2 for adult
                    "weight": 200,      // [number, optional] weight (if type=0 in g; else in Kg)
                    "age": 3            // [number, optional] age
                },
                "ERRecord" : [
                    {
                        "recordTime" : 1444638128,  //記錄時間[number(timestamp)]
                        "itemCode" : "SCON1A"   //記錄項目代碼(須參照急救項目文件)[string]
                    },
                    {
                        "recordTime" : 1444638130,  //記錄時間[number(timestamp)]
                        "itemCode" : "SCPRET",
                        "value" : "10.2"    //記錄項目使用者輸入數值，當使用者有填數值時回傳[string, optional]
                    },
                    {
                        "recordTime" : 1444638135,  //記錄時間[number(timestamp)]
                        "itemCode" : "ASUFO"
                    },
                    {
                        "recordTime" : 1444638140,  //記錄時間[number(timestamp)]
                        "itemCode" : "ROSC",
                        "appendData" : {    //附屬欄位(ROSC,terminate使用)[object, optional]
                            "vitalSignSPB": [       //收縮壓
                                "100"
                            ],
                            "vitalSignDPB":[    //舒張壓
                                "70"
                            ],
                            "vitalSignHR":[    //心跳
                                "40"
                            ],
                            "vitalSignSpO2":[    //SpO2
                                "10"
                            ],
                            "vitalSignEtCO2":[    //EtCO2
                                "10"
                            ],
                            "vitalSignRR":[    //呼吸
                                "20"
                            ],
                            "rhytm" : [
                                "Sinus Rhythm",
                                "Sinus tachycardia",
                                "Sinus bradycardia",
                                "AIVR",
                                "Af/AF",
                                "MAT",
                                "Juntional",
                                "使用者填入的其他原因"
                            ],
                            "management" : [
                                "ECMO",
                                "IABP",
                                "Hypothermia",
                                "Tracheostomy",
                                "TCP",
                                "Pericardiocentesis",
                                "Nil",
                                "使用者填入的其他原因"
                            ],
                            "neurologicalOutcomeGCSE" : [
                                "1"
                            ],
                            "neurologicalOutcomeGCSV" : [
                                "1"
                            ],
                            "neurologicalOutcomeGCSM" : [
                                "1"
                            ],
                            "neurologicalOutcomePupilRight" : [
                                "1"
                            ],
                            "neurologicalOutcomePupilLeft" : [
                                "1"
                            ],
                            "neurologicalOutcomeLightRight" : [ //光反射左
                                "1"
                            ],
                            "neurologicalOutcomeLightLeft" : [  //光反射右
                                "1"
                            ],
                            "diposition" : [
                                "加護病房",
                                "留原單位",
                                "重症區"
                            ]
                        }
                    },
                    {
                        "recordTime" : 1444638150,  //記錄時間[number(timestamp)]
                        "itemCode" : "terminate",
                        "appendData" : {    //附屬欄位(ROSC,terminate使用)[object, optional]
                            "reason" : [
                                "Futile",   //使用者有選擇或填寫時回傳
                                "DNR"
                            ],
                            "EtCO2" : [
                                "10.2"
                            ],
                            "rhytm" : [
                                "PEA",
                                "VT",
                                "VF",
                                "Asytole",
                                "使用者填入的其他原因"
                            ]
                        }
                    }
                ]
            },
            "device" : "10.1.1.1",  //裝置IP
            "empNo": "111281",  //員工編號
            "recordNo": "THE_ID_FOR_THE_RECORD",                // [string, optional] 修改的時候使用
            "sessionKey": "DD07A0AF4E9F426C838185D8DD19EFE2"
        }

+ Response 200 (application/json)


        {
            "success": true,
            "content": {
                "recordNo": "A12-40322"      // The identifier for the newly created ER record [string]
            }
        }

+ Response 400 (application/json)

        {
            "error": 701,
            "message": "缺少參數xxx"
        }

+ Response 400 (application/json)


        {
            "error": 702,
            "message": "參數xxx 型態錯誤"
        }

+ Response 403 (application/json)


        {
            "error": 103,
            "message": "無存取權限"
        }
