# Group MedicationOrder

## 處方醫令資訊 [/medicationOrder/{medicationCode}{?sessionKey,stateIndex,accountNo}]
### 取得處方醫令屬性資料 [GET]
+ Parameters
    + sessionKey    (string) ... SessionKey
    + stateIndex    (number) ... 請求階段 index 開始為 0
    + accountNo     (string) ... 病患的 account number

+ Response 200 (application/json)


        {
            "content": {
                "medicationCode":           "T0_P1110023",            // [string] 處方代碼 院區碼_ID
                "medicationName":           "TEST_ORDER_NAME",        // [string] 處方名稱
                "medicationType":           "N",                      // [string] 處方類別 如一般為 N 注射為 I
                "doseUnit":                 "mg",                     // [string] 藥品劑量使用單位名稱
                "packUnit":                 "mg",                     // [string] 藥品包裝劑量使用單位名稱
                "packConvertRate":          1,                        // [number] 一個包裝內有幾個 dose unit
                "billType":                 "Z",                      // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "createdTime":              1435744800,               // [number(timestamp)] 此項處方醫令編輯起始時間 (UI 介面顯示用)
                "specialDose":              "TEXT_CONTENT ...",       // [string, optional] 特殊劑量 若無則不用回傳
                "repeatReason":             "TEXT_CONTENT ...",       // [string, optional] 用要原因 若無則不用回傳
                "isAllergic":               false,                    // [boolean] 過敏 是否需要預設勾選
                "isADR":                    false,                    // [boolean] ADR 是否預設勾選
                "supportedRoutes":  [                                 // [optional] 注射處方使用 若沒有對應的途徑則不用回傳
                    "IF",                                             // [string] 途徑代碼
                    "IV",
                    "cIF",
                    ...
                ],
                "hiddenRoutes": [                                     // [optional] 注射處方使用 隱藏的途徑清單 若沒有不用回傳
                    "LL",
                    ...
                ],
                "diluentInstructions": {                              // [optional] 稀釋液指示 注射處方式使用
                    "default": [                                      // [optional] 預設稀釋液選項 若無不用回傳
                        "NS",
                        "D5W",
                        ...
                    ],
                    "IF": {                                           // [optional] 對應的鍵值為路徑代碼，陣列內容為該路徑所支援的稀釋液
                        "options": [
                            "NS",                                     // [string] 稀釋液
                            "LR",
                            ...
                        ],
                        "default": "NS",                              // [string] 預設選取稀釋液
                        "othersEnable": false,                        // [boolean] 是否可以輸入其他稀釋液
                        "displayOptions": "1122",                     // [string] 顯示輸注說明欄位代碼 1: 顯示但不可編輯 2: 可編輯 0: 不顯示
                        "volumeSug": {                                // [optional] 容量輸注指示
                            "max": 1000,
                            "min": 10,
                            "unit": "ml"
                        },
                        "concentrationSug": {                         // [optional] 濃度輸注指示
                            "max": 100,
                            "min": 20,
                            "unit": "ml/minute"
                        },
                        "InfusionTimeSug": {                          // [optional] 輸注時間指示
                            "max": 20,
                            "min": 5,
                            "unit": "min"
                        },
                        "VelocitySug": {                              // [optional] 流速指示
                            "max": 300,
                            "min": 30,
                            "unit": "ml/Hr"
                        }
                    },
                    ...
                }
            }
        }

+ Response 400 (application/json)

        {
            "error": 804,                       // [number] error code
            "content": {
                "message": "TEST_MESSAGE"       // [string] error message
            }
        }


+ Response 400 (application/json)

        {
            "error": 805,                                       // [number] error code
            "content": {
                "message": "THE MESSAGE TO DISPLAY",            // [string] error message to display
                "link": "EXTERNAL LINK"                         // [string] the redirect link for the Safari
            }
        }

## 6/25 - 醫令碼所對應的醫令 [/medicationOrder/{medicationCode}/defaultValues{?sessionKey,accountNo,searchType,patientClass,orderIdse,planDate,orderStage,planExecutionTime}]
### 取得醫令範本的預設值 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey
    + accountNo         (string) ... 帳號
    + searchType        (string) ... 搜尋類別來源 P,  A
    + patientClass      (string) ... 門住急別
    + orderIdse         (string, optional) ... 搜尋藥囑額外識別碼

+ Response 200 (application/json)

        {
            "content": [
                {
                    "medicationCode": "T0_3211234_L",                 // [string] 對應的 orderCode 以供處理虛擬醫囑時使用
                    "diluentAbbreviation": "稀釋液簡稱",               // [string, optional] 預設稀釋液簡稱 ???
                    "diluentVolume": 10,                             // [number, optional] 預設稀釋液體積
                    "dose": 10,                                      // [number, optional] 預設劑量
                    "specialInstruction": "xxx",                     // [string, optional] 預設特殊醫囑
                    "infusionTime": 10,                              // [number, optional] 預設輸注時間
                    "mlPerHour":  1,                                 // [number, optional] 預設流速
                    "OrderStage": "階段",                            // [string, optional] ???
                    "repeatedPattern": "QD",                        // [string, optional] 預設頻率
                    "route": "IF",                                  // [string, optional] 預設途徑
                    "useDays": 1,                                   // [number, optional] 預設􏲟開藥天數
                    "orderReason":  "xxx"                           // [string, optional] 用藥原因 (例如事前檢核帶入的結果)
                },
                ...
            ]
        }


## 處方醫令開令記錄 [/account/{accountNo}/medicationRecords{?sessionKey,stateIndex,medicationRecordId}]
### 開立處方醫令 [POST]

+ Request IssueMedicationOrder (application/json)

        {
            "content": {
                "medicationCode":   "P1110023",                     // [string] 欲開立之處方代碼
                "hospitalCode":     "HQ",                           // [string] 院區代碼
                "stage":            "regular",                      // [string] 階段
                "dose":             "1",                            // [string] 劑量
                "route":            "IF",                           // [string] 路徑代碼
                "repeatedPattern":  "QD",                           // [string] 頻率代碼
                "useDays":          0,                              // [number] 使用天數
                "billType":         "Z",                            // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "state":            false,                          // [boolean] STATE 選項是否被勾選
                "startDate":        "20150702",                     // [string] 起始日期，依照格式 yyyymmDD
                "startTime":        9,                              // [number] 起始時間 (小時, 24 時制)
                "endDate":          "20150709",                     // [string, optional] 結束日期，依照格式 yyyymmDD 若使用者沒輸入不會傳入
                "endTime":          9,                              // [number, optional] 結束時間 (小時, 24 時制) 若使用者沒輸入不會傳入
                "specialDose":      "TEXT CONTENT ...",             // [string, optional] 特殊劑量 若使用者沒輸入不會傳入
                "repeatReason":     "TEXT CONTENT ...",             // [string, optional] 使用原因 若使用者沒輸入不會傳入
                "isAllergic":       false,                          // [boolean] 過敏
                "isADR":            false,                          // [boolean] ADR
                "diluent":          {  // [optional] 稀釋液 注射處方使用
                    "code":     "12332123",                         // [string] 稀釋液代碼
                    "volume":   100                                 // [number] 稀釋液體積
                },
                "injection": {  // [optional] 注射處方指示
                    "concentration":    100,                        // [number] 濃度 注射處方使用
                    "flowVelocity":     100,                        // [number] 速度 注射處方使用
                    "infusionTime":     10,                         // [number] 輸注時間 注射處方使用
                    "mlPerHour":        1                           // [number] 流速 注射處方使用
                },
                "dispenseWay":  1,                                  // [number, optional] 調劑方式
                "dispenseDayList": [                                // [optional] 調劑指定日期
                    "20150707",                                     // [string] 調劑日期 依照格式 yyyymmDD
                    "20150714",
                    "20150721",
                    ...
                ],
                "dailyAmmount": 5                                   // [number, optional] 每日劑量, 若無則不會傳入
            },
            "stateIndex": 0,                                        // [number] 交易狀態的 state 從 0 開始
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"        // [string] SessionKey
        }

+ Response 201 (application/json)

        {
            "success": true,
            "content": {
                "medicationRecordId": "123123"      // [string] 交易記錄ID
            }
        }

+ Response 400 (application/json)

        {
            "error": 804,                           // [number] ErrorCode
            "content": {                            // The content to help the client to handle the error response
                "stateIndex":  1,                   // [number]
                "message": "Validation XXX failed"  // [string] error description
            }
        }

### 刪除醫令處方 [DELETE]
+ Parameters
    + sessionKey            (string) ... SessionKey
    + medicationRecordId    (string) ... 欲刪除之醫令交易記錄 ID

+ Response 200 (application/json)

        {
            "success": true
        }


## 特殊劑量常用選項表 [/medicationOrder/specialDoseOptions{?sessionKey}]
### 取得選項內容 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": [
                "早__{%f:dose1}__ __{%u}__, 午__{%f:dose2}__ __{%u}__, 晚__{%f:dose3}__ __{%u}__, 睡前__{%f:dose3}__ __{%u}__, __{%p:selection:飯前:飯後}__ ",
                "__{%t:time1}__ __{%u}__, __{%t:time2}__ __{%u}__, __{%t:time3}__ __{%u}__, __{%t:time4}__ __{%u}__",
                "指定用法: __{%s:content}__",
                "一日 __{%f:dose1}__ __{%u}__, 隔日 __{%f:dose2}__ __{%u}__交替使用, __{%p:timeSelection:早(9AM):午(1PM):晚(6PM):睡前(9PM)}__",
                "周一 __{%f:mon}__ __{%u}__, 周二 __{%f:tue}__ __{%u}__, 周三 __{%f:wed}__ __{%u}__, 周四 __{%f:thu}__ __{%u}__, 周五 __{%f:fri}__ __{%u}__, 周六 __{%f:sat}__ __{%u}__, 周日 __{%f:sun}__ __{%u}__, __{%p:timeSelection:早(9AM):午(1PM):晚(6PM):睡前(9PM)}__",
                ...
            ]
        }

## 處方頻率表 [/medicationOrder/repeatedPatterns{?sessionKey}]
### 取得處方頻率表 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": [
                {
                    "code":         "QD",           // [string] 頻率代碼
                    "name":         "QD",           // [string] 頻率名稱
                    "daysOfPeriod":  7,             // [number] 週期天數 一個週期幾天
                    "daysPerPeriod": 1,             // [number] 週期內服用天數
                    "timesPerDay":   1,             // [number] 每日次數
                    "timeOptions": [                // [optional] 如果沒有就不回傳
                        9,
                        18,
                        ...
                    ]
                },
                ...
            ]
        }

## 平板無法開立藥品品項之外部連結 [/medicationOrder/externalLinks{?sessionKey,hospitalCode}]
### 取得連結 [GET]

+ Parameters
    + sessionKey (string)   ... SessionKey
    + hospitalCode (string) ... 院區碼

+ Response 200 (application/json)

        {
            "content": {
                "TPN": "THE EXTERNAL LINK FOR TPN",         // [string] TPN 藥品外部連結的 base url
                ...
            }
        }

## 藥囑交易記錄之暫停醫囑相關資訊 [/account/{accountNo}/medicationRecord/{medicationRecordId}/holdInfo{?sessionKey}]
### 取得藥囑暫停功能相關資訊 [GET]

+ Parameters
    + sessionKey (string) ...   SessionKey

+ Response 200 (application/json)

        {
            "content": {
                "description": "Alparazalam ((管4)) 安博寧",         // [string] 暫停醫囑相關資訊
                "unit": "Dose",                                     // [string] 暫停醫囑使用單位
                "optionas": [
                    1,                                              // [number] 暫停醫囑選項清單
                    2,
                    ...
                ],
                "executionTimes": [
                    1406938026,                                     // [number(timestamp)] 開始時間選項
                    1406948026,                                     // [number(timestamp)]
                    1406958026,                                     // [number(timestamp)]
                    ...
                ],
                "canRestart": false,                                // [boolean] 此藥囑交易記錄是否可以開立重啟醫囑
                "holdRecords": [                                    // 已經開立的 暫停/重啟 醫囑清單，沒有則回傳空陣列
                    {
                        "creator": "111271",            // [string] 開立人之員工編號
                        "createdTime": 1406938026,      // [number(timestamp)] 醫囑開立時間
                        "executionTime": 1406938026,    // [number(timestamp), optional] 執行開始時間 暫停醫囑使用
                        "type": 0,                      // [number] 暫停醫囑: 0 重啟醫囑: 1
                        "verifier": "111281",           // [string,optional] 確認者, 若無不用回傳
                        "option": 1,                    // [number, optional] 暫停醫囑選項 重啟醫囑不用回傳
                        "recordId": "13-01"             // [string] 暫停/重啟 醫囑交易記錄 ID
                    },
                    ...
                ]
            }
        }


## 修改醫囑 [PUT]

+ Request IssueMedicationOrder (application/json)

        {
            "content": {
                "medicationCode":   "P1110023",                     // [string] 欲開立之處方代碼
                "hospitalCode":     "HQ",                           // [string] 院區代碼
                "stage":            "regular",                      // [string] 階段
                "dose":             "1",                            // [string] 劑量
                "route":            "IF",                           // [string] 路徑代碼
                "repeatedPattern":  "QD",                           // [string] 頻率代碼
                "useDays":          0,                              // [number] 使用天數
                "billType":         "Z",                            // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "state":            false,                          // [boolean] STATE 選項是否被勾選
                "startDate":        "20150702",                     // [string] 起始日期，依照格式 yyyymmDD
                "startTime":        9,                              // [number] 起始時間 (小時, 24 時制)
                "endDate":          "20150709",                     // [string, optional] 結束日期，依照格式 yyyymmDD 若使用者沒輸入不會傳入
                "endTime":          9,                              // [number, optional] 結束時間 (小時, 24 時制) 若使用者沒輸入不會傳入
                "specialDose":      "TEXT CONTENT ...",             // [string, optional] 特殊劑量 若使用者沒輸入不會傳入
                "repeatReason":     "TEXT CONTENT ...",             // [string, optional] 使用原因 若使用者沒輸入不會傳入
                "isAllergic":       false,                          // [boolean] 過敏
                "isADR":            false,                          // [boolean] ADR
                "diluent":          {  // [optional] 稀釋液 注射處方使用
                    "code":     "12332123",                         // [string] 稀釋液代碼
                    "volume":   100                                 // [number] 稀釋液體積
                },
                "injection": {  // [optional] 注射處方指示
                    "concentration":    100,                        // [number] 濃度 注射處方使用
                    "flowVelocity":     100,                        // [number] 速度 注射處方使用
                    "infusionTime":     10,                         // [number] 輸注時間 注射處方使用
                    "mlPerHour":        1                           // [number] 流速 注射處方使用
                },
                "dispenseWay":  1,                                  // [number, optional] 調劑方式
                "dispenseDayList": [                                // [optional] 調劑指定日期
                    "20150707",                                     // [string] 調劑日期 依照格式 yyyymmDD
                    "20150714",
                    "20150721",
                    ...
                ],
                "dailyAmmount": 5                                   // [number, optional] 每日劑量, 若無則不會傳入
            },
            "stateIndex": 0,                                        // [number] 交易狀態的 state 從 0 開始
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"        // [string] SessionKey
        }

+ Response 200 (application/json)

        {
            "success": true
        }


## 藥囑交易記錄之暫停和重啟醫囑清單 [/account/{accountNo}/medicationRecord/{medicationRecordId}/holdOrders{?sessionKey}]
### 開立暫停/重啟醫囑 [POST]

+ Request IssueHoldOrder (application/json)

        {
            "content": {
                "creator": "111287",                // [string] 開立人
                "executionTime": 1406948026,        // [number(timestamp), optional] 執行開始時間 暫停醫囑使用
                "option": 10,                       // [number, optional] 暫停醫囑選項(值)
                "type": 0                           // [number] 醫囑種類 暫停醫囑為 0 重啟醫囑為 1
            },
            "sessionKey": "1112131321aqwdqwd"       // [string] SessionKey
        }

+ Response 200 (application/json)

        {
            "success": true,
            "content": {
                "recordId": "13-8"     // 本次編輯後的 暫停/重啟 醫囑記錄 ID
            }
        }



## 10/27 確認多筆病患醫令記錄 [/medication/confirmation/batch]
### 確認多比病患醫令記錄 [POST]
+ Request Confirm orderRecord(s)

        {
            "sessionKey": "DE44A33624064BFCB0BBAFDB9A509C16",
            "requests": [
                {
                    "requestId": "request_001",
                    "path": "/account/{accountNo}/orderRecord/T32132012",
                    "method": "PATCH",
                    "body": {
                        "content": {
                            "confirmedTime": 1438423200,         // [number(timestamp)] 確認時間
                            "verifier": "111283"                 // [string]  確認醫師員工編號
                        }
                    }
                },
                {
                    "requestId": "request_001",
                    "path": "/account/{accountNo}/orderRecord/T32132013",
                    "method": "PATCH",
                    "body": {
                        "content": {
                            "confirmedTime": 1438423200,         // [number(timestamp)] 確認時間
                            "verifier": "111283"                 // [string]  確認醫師員工編號
                        }
                    }
                },
                ...
            ]
        }

+ Response 200 (application/json)


        {
            "requests": [
                {
                    "requestId": "request001",
                    "success": true
                },
                {
                    "requestId": "request002",
                    "success": true
                }
                ...
            ]
        }
