# Group 多媒體相關 Media Relative Service
## 6/5 - ProgressNote 上傳 [/patients/{chartNo}/progressNote{?title,accountNo,uploader,description,reviewer}]
### 新增 ProgressNote [POST]
Content-type: multipart/form-data 影像用 [filename]: [content] 形式上傳

+ Parameters
    + title (string)                ... ProgressNote 標題
    + accountNo (string)            ... 帳號編號
    + uploader (string)             ... 上傳者之員工編號
    + description (string)          ... 上傳之 ProgressNote 之描述
    + reviewer (string, optional)   ... 欲請求簽章之員工編號

+ Response 200 (application/json)


        {
            "success": true
        }

## 6/5 - 暫存空間照片上傳 [/patients/{chartNo}/tempStorage{?uploader}]
### 新增照片至暫存空間 [POST]
Content-type: multipart/form-data 影像用 [filename]: [content] 形式上傳

+ Parameters
    + uploader (string)             ... 上傳者之員工編號

+ Response 200 (application/json)

        {
            "success": true
        }
