# Group MedicationOrder

## 處方醫令資訊 [/medication/{medicationCode}{?sessionKey,stateIndex}]
### 取得處方醫令屬性資料 [GET]
+ Parameters
    + sessionKey    (string) ... SessionKey
    + stateIndex    (number) ... 請求階段 index 開始為 0

+ Response 200 (application/json)


        {
            "content": {
                "medicationCode":           "P1110023",               // [string] 處方代碼
                "medicationName":           "TEST_ORDER_NAME",        // [string] 處方名稱
                "medicationType":           "N",                      // [string] 處方類別 如一般為 N 注射為 I
                "doseUnit":                 "mg",                     // [string] 藥品劑量使用單位名稱
                "packUnit":                 "mg",                     // [string] 藥品包裝劑量使用單位名稱
                "packConvertRate":          1,                        // [number] 一個包裝內有幾個 dose unit
                "defaultDose":              "0.13",                   // [string, optional] 藥品預設劑量 若無則不用回傳
                "defaultRoute":             "IF",                     // [string, optional] 預設途徑代碼 若無則不用回傳
                "defaultRepeatedPattern":   "QD",                     // [string, optional] 預設頻率代碼 若無則不用回傳
                "defaultUseDays":           0,                        // [number] 預設使用天數 若無則不用回傳
                "billType":                 "Z",                      // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "createdTime":              1435744800,               // [number(timestamp)] 此項處方醫令編輯起始時間 (UI 介面顯示用)
                "specialDose":              "TEXT_CONTENT ...",       // [string, optional] 特殊劑量 若無則不用回傳
                "repeatReason":             "TEXT_CONTENT ...",       // [string, optional] 用要原因 若無則不用回傳
                "isAllergic":               false,                    // [boolean] 過敏 是否需要預設勾選
                "isADR":                    false,                    // [boolean] ADR 是否預設勾選
                "supportedRoutes":  [                                 // [optional] 注射處方使用 若沒有對應的途徑則不用回傳
                    "IF",                                             // [string] 途徑代碼
                    "IV",
                    "cIF",
                    ...
                ],
                "hiddenRoutes": [                                     // [optional] 注射處方使用 隱藏的途徑清單 若沒有不用回傳
                    "LL",
                    ...
                ],
                "diluentInstructions": {                              // [optional] 稀釋液指示 注射處方式使用
                    "default": [                                      // [optional] 預設稀釋液選項 若無不用回傳
                        "NS",
                        "D5W",
                        ...
                    ],
                    "IF": {                                           // [optional] 對應的鍵值為路徑代碼，陣列內容為該路徑所支援的稀釋液
                        "options": [
                            "NS",                                     // [string] 稀釋液
                            "LR",
                            ...
                        ],
                        "default": "NS",                              // [string] 預設選取稀釋液
                        "othersEnable": false,                        // [boolean] 是否可以輸入其他稀釋液
                        "displayOptions": "1122",                     // [string] 顯示輸注說明欄位代碼 1: 顯示但不可編輯 2: 可編輯 0: 不顯示
                        "volumeSug": {                                // [optional] 容量輸注指示
                            "max": 1000,
                            "min": 10,
                            "unit": "ml"
                        },
                        "concentrationSug": {                         // [optional] 濃度輸注指示
                            "max": 100,
                            "min": 20,
                            "unit": "ml/minute"
                        },
                        "InfusionTimeSug": {                          // [optional] 輸注時間指示
                            "max": 20,
                            "min": 5,
                            "unit": "min"
                        },
                        "VelocitySug": {                              // [optional] 流速指示
                            "max": 300,
                            "min": 30,
                            "unit": "ml/Hr"
                        }
                    },
                    ...
                }
            }
        }

+ Response 400 (application/json)

        {
            "error": 804,                       // [number] error code
            "content": {
                "message": "TEST_MESSAGE",      // [string] error message
            }
        }


## 處方醫令開令記錄 [/account/{accountNo}/medicationRecords{?sessionKey,stateIndex}]
### 開立處方醫令 [POST]

+ Request IssueMedicationOrder (application/json)

        {
            "content": {
                "medicationCode":   "P1110023",                     // [string] 欲開立之處方代碼
                "hospitalCode":     "HQ",                           // [string] 院區代碼
                "stage":            "regular",                      // [string] 階段
                "dose":             "1",                            // [string] 劑量
                "route":            "IF",                           // [string] 路徑代碼
                "repeatedPattern":  "QD",                           // [string] 頻率代碼
                "useDays":          0,                              // [number] 使用天數
                "billType":         "Z",                            // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "state":            false,                          // [boolean] STATE 選項是否被勾選
                "startDate":        "20150702",                     // [string] 起始日期，依照格式 yyyymmDD
                "startTime":        9,                              // [number] 起始時間 (小時, 24 時制)
                "endDate":          "20150709",                     // [string, optional] 結束日期，依照格式 yyyymmDD 若使用者沒輸入不會傳入
                "endTime":          9,                              // [number, optional] 結束時間 (小時, 24 時制) 若使用者沒輸入不會傳入
                "specialDose":      "TEXT CONTENT ...",             // [string, optional] 特殊劑量 若使用者沒輸入不會傳入
                "repeatReason":     "TEXT CONTENT ...",             // [string, optional] 使用原因 若使用者沒輸入不會傳入
                "isAllergic":       false,                          // [boolean] 過敏
                "isADR":            false,                          // [boolean] ADR
                "diluent":          {  // [optional] 稀釋液 注射處方使用
                    "code":     "12332123",                         // [string] 稀釋液代碼
                    "volume":   100                                 // [number] 稀釋液體積
                },
                "injection": {  // [optional] 注射處方指示
                    "concentration":    100,                        // [number] 濃度 注射處方使用
                    "flowVelocity":     100,                        // [number] 速度 注射處方使用
                    "infusionTime":     10,                         // [number] 輸注時間 注射處方使用
                    "mlPerHour":        0.01,                       // [number] 流速 注射處方使用
                },
                "dispenseWay":  1,                                  // [number, optional] 調劑方式
                "dispenseDayList": [                                // [optional] 調劑指定日期
                    "20150707",                                     // [string] 調劑日期 依照格式 yyyymmDD
                    "20150714",
                    "20150721",
                    ...
                ]
            },
            "stateIndex": 0,                                        // [number] 交易狀態的 state 從 0 開始
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"        // [string] SessionKey
        }

+ Response 201 (application/json)

        {
            "success": true,
            "content": {
                "medicationRecordId": "123123",     // [string] 交易記錄ID
            }
        }

+ Response 400 (application/json)

        {
            "error": 804,                           // [number] ErrorCode
            "content": {                            // The content to help the client to handle the error response
                "stateIndex":  1,                   // [number]
                "message": "Validation XXX failed"  // [string] error description
            }
        }


## 特殊劑量常用選項表 [/medication/specialDoseOptions{?sessionKey}]
### 取得選項內容 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": [
                "早 __{%f:dose1}__ 微克, 午 __{%f:dose2}__ 微克, 晚 __{%f:dose3}__ 微克, 睡前 __{%f:dose3}__ 微克, __{%p:selection}__ 飯前 __{%p:selection}__ 飯後",
                "__{%t:time1}__ 微克, __{%t:time2}__ 微克, __{%t:time3}__ 微克, __{%t:time4}__ 微克.",
                "指定用法: __{%s:content}__",
                "一日 __{%f:dose1}__ 微克, 隔日 __{%f:dose2}__ 微克交替使用. __{%p:timeSelection}__ 早(9AM) __{%p:timeSelection}__ 午(1PM) __{%p:timeSelection}__ 晚(6PM) __{%p:timeSelection}__ 睡前(9PM)",
                "周一 __{%f:mon}__ 微克, 周二 __{%f:tue}__ 微克, 周三 __{%f:wed}__ 微克, 周四 __{%f:thu}__ 微克, 周五 __{%f:fri}__ 微克, 周六 __{%f:sat}__ 微克, 周日 __{%f:sun}__ 微克. __{%p:timeSelection}__ 早(9AM) __{%p:timeSelection}__ 午(1PM) __{%p:timeSelection}__ 晚(6PM) __{%p:timeSelection}__ 睡前(9PM)",
                ...
            ]
        }

## 處方頻率表 [/medication/repeatedPatterns{?sessionKey}]
### 取得處方頻率表 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": [
                {
                    "code":         "QD",           // [string] 頻率代碼
                    "name":         "QD",           // [string] 頻率名稱
                    "daysOfPeriod":  7,             // [number] 週期天數 一個週期幾天
                    "daysPerPeriod": 1,             // [number] 週期內服用天數
                    "timesPerDay":   1,             // [number] 每日次數
                    "timeOptions": [                // [optional] 如果沒有就不回傳
                        9,
                        18,
                        ...
                    ],
                },
                ...
            ]
        }
