# Group MedicationOrder

## 處方醫令資訊 [/medication/{medicationCode}{?sessionKey}]
### 取得處方醫令屬性資料 [GET]
+ Parameters
    + sessionKey    (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": {
                "medicationCode":           "P1110023",               // [string] 處方代碼
                "medicationName":           "TEST_ORDER_NAME",        // [string] 處方名稱
                "medicationType":           "N",                      // [string] 處方類別 如一般為 N 注射為 I
                "doseUnit":                 "mg",                     // [string] 藥品劑量使用單位名稱
                "packUnit":                 "mg",                     // [string] 藥品包裝劑量使用單位名稱
                "defaultDose":              "0.13",                   // [string, optional] 藥品預設劑量 若無則不用回傳
                "defaultRoute":             "IF",                     // [string, optional] 預設途徑代碼 若無則不用回傳
                "defaultRepeatedPattern":   "QD",                     // [string, optional] 預設頻率代碼 若無則不用回傳
                "defaultUseDays":           0,                        // [number] 預設使用天數 若無則不用回傳
                "billType":                 "Z",                      // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "createdTime":              1435744800,               // [number(timestamp)] 此項處方醫令編輯起始時間 (UI 介面顯示用)
                "specialDose":              "TEXT_CONTENT ...",       // [string, optional] 特殊劑量 若無則不用回傳
                "repeatReason":             "TEXT_CONTENT ...",       // [string, optional] 用要原因 若無則不用回傳
                "isAllergic":               false,                    // [boolean] 過敏 是否需要預設勾選
                "isADR":                    false                     // [boolean] ADR 是否預設勾選
                "supportedRoutes":  [ // [optional] 注射處方使用 若沒有對應的途徑則不用回傳
                    "IF",                                     // [string] 途徑代碼
                    "IV",
                    "cIF",
                    ...
                ],
                "diluentOptions": [  // [optional] 注射處方使用 若沒有對應的稀釋液不用回傳
                    {
                        "code": "1233213",                  // [string] 稀釋液代碼
                        "name": "DILUENT_001",              // [string] 稀釋液名稱
                    },
                    ...
                ],
                "defaultDiluent": { // [optional] 注射處方使用 若沒有則不用回傳
                    "code": "123123",                       // [string] 稀釋液代碼
                    "name": "DILUENT_001"                   // [string] 稀釋液名稱
                }
            }
        }


## 處方醫令開令記錄 [/account/{accountNo}/medicationRecords{?sessionKey,stateIndex}]
### 開立處方醫令 [POST]

+ Request IssueMedicationOrder (application/json)

        {
            "content": {
                "medicationCode":   "P1110023",                     // [string] 欲開立之處方代碼
                "hospitalCode":     "HQ",                           // [string] 院區代碼
                "stage":            "regular",                      // [string] 階段
                "dose":             "1",                            // [string] 劑量
                "route":            "IF",                           // [string] 路徑代碼
                "repeatedPattern":  "QD",                           // [string] 頻率代碼
                "useDays":          0,                              // [number] 使用天數
                "billType":         "Z",                            // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "state":            false,                          // [boolean] STATE 選項是否被勾選
                "startDate":        "20150702",                     // [string] 起始日期，依照格式 yyyymmDD
                "startTime":        9,                              // [number] 起始時間 (小時, 24 時制)
                "endDate":          "20150709",                     // [string, optional] 結束日期，依照格式 yyyymmDD 若使用者沒輸入不會傳入
                "endTime":          9,                              // [number, optional] 結束時間 (小時, 24 時制) 若使用者沒輸入不會傳入
                "specialDose":      "TEXT CONTENT ...",             // [string, optional] 特殊劑量 若使用者沒輸入不會傳入
                "repeatReason":     "TEXT CONTENT ...",             // [string, optional] 使用原因 若使用者沒輸入不會傳入
                "isAllergic":       false,                          // [boolean] 過敏
                "isADR":            false,                          // [boolean] ADR
                "diluent":          {  // [optional] 稀釋液 注射處方使用
                    "code":     "12332123",                         // [string] 稀釋液代碼
                    "volume":   100                                 // [number] 稀釋液體積
                },
                "injection": {  // [optional] 注射處方指示
                    "concentration":    100,                        // [number] 濃度 注射處方使用
                    "flowVelocity":     100,                        // [number] 速度 注射處方使用
                    "infusionTime":     10,                         // [number] 輸注時間 注射處方使用
                    "mlPerHour":        0.01,                       // [number] 流速 注射處方使用
                }
            },
            "stateIndex": 0,                                        // [number] 交易狀態的 state 從 0 開始
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"        // [string] SessionKey
        }

+ Response 201 (application/json)

        {
            "success": true
            "content": {
                "medicationRecordId": "123123",     // [string] 交易記錄ID
            }
        }

+ Response 400 (application/json)

        {
            "error": 901,                           // [number] ErrorCode
            "content": {                            // The content to help the client to handle the error response
                "stateIndex":  1,                   // [number]
                "message": "Validation XXX failed"  // [string] error description
            }
        }
