# Group 開發中 Phase2 Order APIs

## 7/21 - 科部清單 [/departments{?sessionKey,hospitalCode,patientClass}]
### 取得科部清單 [GET]

+ Parameters
    + sessionKey    (string) ... SessionKey
    + hospitalCode  (string) ... 院區碼
    + patientClass  (string) ... 病患門住急別

+ Response 200 (application/json)

        {
            "content": [
                {
                    "title": "內科",                  // [string] 顯示的 title 名稱
                    "code": "DEPT_001"               // [string] 科部對應的代碼
                },
                {
                    "title": "外科",
                    "code": "DEPT_002"
                },
                ...
            ]
        }

## 7/21 - 醫令套餐 [/orderPackages{?patientClass,type,department,wardCode,pathCode,accountNo,hospitalCode,sessionKey}]
### 取得醫令套餐清單 [GET]

+ Parameters
    + patientClass  (string) ... 病患門住急別 I 為住院 E 為急診
    + hospitalCode  (string) ... 院區別 如 台大本院為 T0
    + department    (string, optional) ... 欲搜尋套餐之科部
    + wardCode      (string, optional) ... 欲搜尋套餐之病房
    + accountNo     (string, optional) ... 欲搜尋病患之帳號
    + type          (string) ... 'category' 為 全部, 檢驗, 檢查, 影醫, 核醫, 病理, 治療, 醫囑 'ward' 為病房 'department' 為科部 'employment' 為員工 'path' 為路徑
    + sessionKey    (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content" : [
                {
                    "packageName": "科部",                                       // [string] 顯示的title名
                    "packageCode": "the_package_code",                          // [string, optional] 透過此碼查詢醫令
                    "preset" : true,                                            // [boolean, optional] 預設選項，使用者選擇上一層選項之後，要預設選取的項目 [
                    "children" : [ // [duplicate, optional]
                        {
                            "packageName": "內科部",                             // 顯示的title名  [string]
                            "preset": true,                                     // [boolean, optional]
                            "children" : [  // 如果有sublist的話, 則顯示此key  [duplicate, optional]
                                {
                                    "packageName": "骨髓移植 BMT",
                                    "preset": true,                             // [boolean, optional]
                                    "children": [  // [duplicate, optional]
                                        {
                                            "packageName" : "Admission Orders", // [string]
                                            "packageCode" : "admissionorder",   // 透過此碼查詢醫令 [string, optional]
                                            "preset" : true                     // [boolean, optional]
                                        },
                                        {
                                            "packageName" : "Admission Lab",    // [string]
                                            "packageCode" : "admissionlab"      // [string, optional]
                                        },
                                        {
                                            "packageName" : "Routine Lab",      // [string]
                                            "packageCode" : "routinelab"        // [string, optional]
                                        },
                                        {
                                            "packageName" : "CPCR",             // [string]
                                            "packageCode" : "cpcr"              // [string, optional]
                                        },
                                        ...
                                    ]
                                }, ...
                            ]
                        }, ...
                    ]
                },
                {
                    "packageName" : "病房",
                    "children" : [ // [optional]
                        {
                            "packageName" : "Major Burn",
                            "children" : [ // [optional]
                                {
                                    "packageName" : "照會",
                                    "packageCode" : "A1234"
                                },
                                {
                                    "packageName" : "醫囑",
                                    "packageCode" : "A1235"
                                },
                                ...
                            ]
                        },
                        ...
                    ]
                },
                ...
            ]
        }


## 7/8 - 醫令搜尋 [/orders{?name,packageCode,patientClass,orderType,hospitalCode,accountNo}]
### 取得藥物清單 [GET]

+ Parameters
    + name (string, optional)           ... 搜尋字串
    + packageCode (string, optional)    ... 套餐
    + orderType (string, optional)      ... 指定要搜尋醫令的醫令種類
    + patientClass (string, optional)   ... 病患的門住急別
    + hospitalCode (string, optional)   ... 院區碼 如台大本院為 T0
    + accountNo (string, optional)      ... 病患帳號

+ Response 200 (application/json)

        {
            "content" : {
                "field" : [
                    {
                        "fieldCode" : "orderType",
                        "displayName" : "醫令類別"
                    },
                    {
                        "fieldCode" : "DisplayCode",
                        "displayName" : "醫令碼"
                    },
                    {
                        "fieldCode" : "order",
                        "displayName" : "醫令內容"
                    },
                    ...
                ],
                "data" : [
                    {
                        "orderCode" : "T000L0114",  // 醫令碼 [string, required]
                        "content" : {
                            "DisplayCode" : "000L0114",
                            "orderType" : "治療",
                            "order"     : "複印全口顎Ｘ光照相"
                        }
                    },
                    {
                        "orderCode" : "T000L0113",
                        "content" : {
                            "DisplayCode" : "000L0113",
                            "orderType" : "治療",
                            "order"     : "複印咬合片Ｘ光照相"
                        }
                    },
                    {
                        "orderCode" : "T000L0112",
                        "content" : {
                            "DisplayCode" : "000L0112",
                            "orderType" : "治療",
                            "order"     : "複印根尖周Ｘ光照相"
                        }
                    },
                    ...
                ]
            }
        }

## 6/29 - 病患 cre 值 [/patients/{chartNo}/cre{?sessionKey}]
### 取得病患 cre 值報告 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": {
                "cre": 31.2
            }
        }

+ Response 404 (application/json)


        {
            "error": 104,                                   // [number] error code
            "message": "找不到病患最近三個月的 cre 數值"         // [string] error message
        }

## 7/07 - 影像醫學介面內容 [/interface/order/MI/{imageType}{?sessionKey,hospitalCode}]
### 取得介面內容 [GET]
+ Parameters
    + sessionKey        (string) ... SessionKey
    + imageType         (string) ... 影像種類，例如 CT, MRI, Plain
    + hospitalCode      (string) ... 醫院院區碼

+ Response 200 (application/json)

        {
            "content": {
                "note": "檢查範圍與內容影像...",                            // [string, optional] 注意事項
                "indicationOptions": [                                    // [optional] indication 所對應的選項，若無則不用回傳
                    {
                        "returnValue": "ind_option_1",                    // [string] 項目所對應之回傳值
                        "displayName": "Follow Up"                        // [string] 項目顯示名稱
                    },
                    ...
                ],
                "groups": [
                    {
                        "title": "Upper Body",                                      // [string, optional] Group 標題 若無則不用回傳
                        "sections": [
                            {
                                "title": "Brain",                                   // [string] Section 標題
                                "sections": [
                                    {
                                        "title": "Routine",                         // [string] 子 Section 標題
                                        "elements": [                               // 子 Section 內可以勾選的項目
                                            {
                                                "title": "Whole Brain",             // [string] 項目名稱
                                                "returnKey": "whole_brain_flag",    // [string] 回傳項目結果時所對應的鍵值
                                                "splitSides": false                // [boolean] 是否要分成左右邊選項 (etc. Plain Film)
                                            }
                                        ]
                                    },
                                    {
                                        "title": "Special",                         // [string] 子 Section 標題
                                        "elements": [                               // 子 Section 內可以勾選的項目
                                            {
                                                "title": "Temporal bone",           // [string] 項目名稱
                                                "returnKey": "temporal_bone_flag",  // [string] 回傳項目結果時所對應的鍵值
                                                "splitSides": false                // [boolean] 是否要分成左右邊選項 (etc. Plain Film)
                                            },
                                            {
                                                "title": "For CT cisternography",   // [string] 項目名稱
                                                "returnKey": "ct_cisternography",   // [string] 回傳項目結果時所對應的鍵值
                                                "splitSides": false                // [boolean] 是否要分成左右邊選項 (etc. Plain Film)
                                            },
                                            ...
                                        ]
                                    },
                                    ...
                                ]
                            },
                            ...
                        ]
                    },
                    ...
                ],
                "others": [  // [optional] 其它可勾選項目，若無則不用回傳
                    {
                        "title": "MR-PET",                                          // [string] 項目名稱
                        "returnKey": "others_mr_pet",                               // [string] 回傳項目結果時所對應的鍵值
                        "splitSides": false                                        // [boolean] 是否要分成左右邊選項 (etc. Plain Film)
                    },
                    ...
                ]
            }
        }


## 6/25 - 醫令碼所對應的醫令 [/order/{orderCode}{?sessionKey}]
### 取得醫令資訊 [GET]

+ Parameters
    + sessionKey        (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": {
                "hospitalCode":     "HQ",               // [string] 院區碼
                "orderCode":        "T123123",          // [string] 醫令碼
                "orderType":        "T",                // [string] 醫令主類別，如治療為 T
                "orderName":        "Testing Order",    // [string] 醫令名稱
                "orderChinName":    "測試醫令",           // [string] 醫令中文名稱
                "screenNote":       "重要提示",           // [string] 重要提示 顯示於介面中
                "isVirtualOrder":   false,              // [boolean] 是否為虛擬醫令
                "isAvailable":      true,               // [boolean] 是否可以使用
                "isOpen":           "OI",               // [string] 註明可用之類別 E 為急診 I 為住院 O 為門診
                "isOpenSelect":     true,               // [boolean] 是否開放選取
                "isEmergency":      true,               // [boolean] 是否支援急做
                "subType":          "N",                // [string, optional] orderType = T 時使用 一般為 N, 手術為 O, 麻醉為 A, 齒位為 D, 技工所為 E, 復健為 P
                "selectable":       true,               // [boolean] 是否可以選取
                "specimenList":     [                   // [optional] orderType = L 時使用
                    {
                        "code": "ts1",                  // [string] 檢體代號
                        "title": "TEST_SPECIMEN_1",     // [string] 檢體名稱
                        "selected": false               // [boolean] 預設選取的時候回傳 True 否則回傳 False
                    },
                    {
                        "code": "ts2",                  // [string] 檢體代號
                        "title": "TEST_SPECIMEN_2",     // [string] 檢體名稱
                        "selected": true                // [boolean] 預設選取的時候回傳 True 否則回傳 False
                    },
                    ...
                ],
                "appendOrders":     [                   // [optional] 附帶醫令，若無則不用回傳
                    {
                        "orderType":    "T",                    // [string] 醫令主類別，如治療為 T
                        "orderCode":    "TSA123zzz",            // [string] 醫令碼
                        "orderName":    "Testing Order2",       // [string] 醫令名稱
                        "quantity":     1,                      // [number] 數量
                        "billType":     "Z",                    // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                        "required":     false                   // [boolean] 是否為必帶醫令
                    },
                    {
                        "orderType":    "P",                    // [string] 醫令主類別
                        "orderCode":    "PZZ123qqq",            // [string] 醫令碼
                        "orderName":    "Testing Order3",       // [string] 醫令名稱
                        "quantity":     4,                      // [number] 數量
                        "billType":     "Z",                    // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                        "required":     true                    // [boolean] 是否為必帶醫令
                    },
                    ...
                ],
                "questionary":      [                   // [optional] 附帶問題內容，若無則不用回傳
                    {
                        "title": "SINGLE_SELECTION",            // [string] 問題顯示題目
                        "returnKey": "s_selection_example",     // [string] 回傳結果時該問題所對應的鍵值
                        "type": "S",                            // [string] 問題種類，如日期為 D，單選為 S
                        "required": true,                       // [boolean] 問題是否為必填項目
                        "defaultPriority": 0,                   // [optional, number] 預設選取項目之順序代號，當類型為 S 或 M 時使用
                        "options": [                            // [optional] 選擇項目列表，當類型為 S, M 時使用
                            {
                                "title": "OPTIONA: A",          // [string] 選項顯示內容
                                "returnValue": "optional_a",    // [string] 回傳時該選項所對應的值
                                "priority": 0                   // [number] 選項顯示順序
                            },
                            {
                                "title": "OPTIONAL: B",         // [string] 項目顯示內容
                                "returnValue": "optiona_b",     // [string] 回傳時該選項所對應的值
                                "priority": 1                   // [number] 項目顯示順序
                            },
                            ...
                        ],
                        "freeSelectionEnable": false            // [optional, boolean] 是否允許增添選項，當類型為 S, M 時使用
                    },
                    {
                        "title": "DATE_SELECTION",              // [string] 問題顯示題目
                        "returnKey": "d_selection_example",     // [string] 回傳結果時該問題所對應的鍵值
                        "type": "D",                            // [string] 問題種類，如日期為 D，單選為 S
                        "required": true,                       // [boolean] 問題是否為必填項目
                        "dateFormat": "DD",                     // [optional, string] 當類型為 D 時使用
                        "defaultDate": 1406938026               // [optional, number(timestamp)] 預設顯示日期，當類型為 D 時使用
                    },
                    {
                        "title": "INPUT_BOX",                   // [string] 問題顯示題目
                        "returnKey": "input_box_example",       // [string] 回傳結果時該問題所對應的鍵值
                        "type": "T",                            // [string] 問題種類，如單行文字框為 T 多行文字框為 P
                        "required": false,                      // [boolean] 問題是否為必填項目
                        "dictionary": [                         // [optional] 常用字彙，當類型為 T 或 P 時可使用
                            "ped_1",
                            "ped_2",
                            "operation_AS1",
                            "operation_AS2",
                            ...
                        ]
                    },
                    {
                        "title": "MULTI_LINE_BOX",              // [string] 問題顯示題目
                        "returnKey": "multi_line_example",      // [string] 回傳結果時該問題所對應的鍵值
                        "type": "P",                            // [string] 問題種類，如單行文字框為 T 多行文字框為 P
                        "required": false,                      // [boolean] 問題是否為必填項目
                        "dictionaryId": "DIC_3201"              // [optional, string] 大型常用字彙對應之編號，當類型為 T 或 P 時可使用
                    },
                    ...
                ]
            }
        }

## 6/16 - 大型常用字彙集 [/questionDictionary/{dictionaryId}{?offset,limit,hospitalCode,sessionKey}]
### 取得 dictionaryId 所對應之大型常用字彙集內容 [GET]
+ Parameters
    + offset        (number) ... 設定回傳資料偏移數
    + limit         (number) ... 設定最大回傳筆數
    + hospitalCode  (string) ... 醫院院區碼
    + sessionKey    (string) ... SessionKey

+ Response 200 (application/json)

        {
            "content": [
                "台灣大學醫學院",         // [string] 字彙選項
                "台灣大學醫學院竹東分院",
                "榮民總醫院",
                ...
            ],
            "total": 10,                // [number] 此次Query總筆數
            "offset": 0,                // [number] 回傳資料偏移數
            "limit": 100                // [number] 最大回傳筆數
        }


## 7/20 病患醫令記錄 [/account/{accountNo}/orderRecords{?orderCode,orderName,sessionKey,orderRecordId}]

### 開立醫令 [POST]

+ Request IssueRegularOrders (application/json)

        {
            "content": { // 開立醫令清單，每個醫令對應的鍵值為該醫令在本次請求中辨識之所用
                "1": {
                    "orderCode": "T00001234",           // [string] 醫令碼
                    "orderName": "TEST_ORDER_001",      // [string] 醫令名稱
                    "hospitalCode": "HQ",               // [string] 院區碼
                    "quantity": 3,                      // [number] 數量
                    "billType": "E",                    // [string] 記帳類別
                    "isEmergency": false,               // [boolean] 是否急做
                    "expectedExTime": 1406938026,       // [number(timestamp)] 預計執行時間
                    "specialInstruction": "Test 1",     // [string] 特殊醫囑
                    "questionary": [                    // [optional] 問答題答案，若無則不會傳入
                        {
                            "returnKey": "d_selection_example",     // [string] 問答題對應鍵值
                            "type": "S",                            // [string] 問答題類型
                            "value": [                              // [optional]
                                0,
                                1,
                                ...
                            ]
                        },
                        {
                            "returnKey": "input_box_example",       // [string] 問答題對應鍵值
                            "type": "T",                            // [string] 問答題類型
                            "value": "this is the input content"    // [optional]
                        }
                    ],
                    "appendOrders": [ // [optional] 附帶醫令，若無則不會傳入
                        "TSA123001",  // [string] 醫令碼
                        "K00123110",
                        ...
                    ]
                },
                "2": {
                    "orderCode": "K00001233",           // [string] 醫令碼
                    "orderName": "TEST_ORDER_002",      // [string] 醫令名稱
                    "hospitalCode": "HQ",               // [string] 院區碼
                    "quantity": 2,                      // [number] 數量
                    "billType": "E",                    // [string] 記帳類別
                    "isEmergency": false,               // [boolean] 是否急做
                    "expectedExTime": 1405238026,       // [number(timestamp)] 預計執行時間
                    "specialInstruction": "Test 2",     // [string] 特殊醫囑
                    "questionary": [                    // [optional] 問答題答案，若無則不會傳入
                        {
                            "returnKey": "d_selection_example",     // [string] 問答題對應鍵值
                            "type": "S",                            // [string] 問答題類型
                            "value": [                              // [optional]
                                0,
                                1,
                                ...
                            ]
                        },
                        {
                            "returnKey": "input_box_example",       // [string] 問答題對應鍵值
                            "type": "T",                            // [string] 問答題類型
                            "value": "this is the input content"    // [optional]
                        }
                    ],
                    "appendOrders": [ // [optional] 附帶醫令，若無則不會傳入
                        "TSA123001",  // [string] 醫令碼
                        "K00123110",
                        ...
                    ]
                },
                "3": {
                    "orderCode": "K00001233",           // [string] 醫令碼
                    "orderName": "TEST_ORDER_002",      // [string] 醫令名稱
                    "hospitalCode": "HQ",               // [string] 院區碼
                    "quantity": 2,                      // [number] 數量
                    "billType": "E",                    // [string] 記帳類別
                    "isEmergency": false,               // [boolean] 是否急做
                    "expectedExTime": 1405238026,       // [number(timestamp)] 預計執行時間
                    "specialInstruction": "Test 3"      // [string] 特殊醫囑
                },
                ...
            },
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009",           // [string] SessionKey
            "forMIOrders": false                                        // [boolean] 是否為請求影像醫學的 order
        }

+ Response 200 (application/json)

        {
            "success": True,
            "content": {
                "orderRecordIds": {
                    "1": "T12312311111",     // [string] 醫令交易檔 ID
                    "2": "K23111222222",     // [string] 醫令交易檔 ID
                    ...
                }
            }
        }

+ Response 400 (application/json)

        {
            "error": 802,
            "content": {
                "succeeded": {  // [optional] 回傳成功開立的醫令之清單，若無則不用回傳
                    "orderRecordIds": {
                        "2": "K23111222222",
                        ...
                    }
                },
                "failed": [     // 未能成功開立的醫令之清單，內容為該醫令所對應之鍵值
                    "1",
                    "3",
                    ...
                ],
                "message": "ERROR DESCRIPTION"  // [string] 有關請求錯誤之描述
            }
        }

### 刪除醫令 [DELETE]
+ Parameters
    + sessionKey    (string) ... SessionKey
    + orderRecordId (string) ... 欲刪除之醫令交易檔 ID

+ Response 200 (application/json)

        {
            "success": true
        }

## 7/20 開立影像醫學醫令 [/account/{accountNo}/orderRecords{?orderCode,sessionKey,orderRecordId}]
### 開立醫令 [POST]

+ Request IssueMedicalImageOrders (application/json)


        {
            "content": {
                "payment": "PAYMENT_SELECTION_SELF",            // [optional] 以下為表格填寫的資料
                "indication": "",                               // [optional]
                "whole_brain_flag": true                        // [optional]
            },
            "imageType": "Plain",                               // [string] 影像類別 MRI, CT 或 Plain
            "forMIOrders": true,                                // [boolean] 是否為請求影像醫學的 order
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"    // [string] SessionKey
        }


+ Response 200 (application/json)

        {
            "success": True,
            "content": {
                "orderRecordIds": {
                    "1": "T12312311111",     // [string] 醫令交易檔 ID
                    "2": "K23111222222",     // [string] 醫令交易檔 ID
                    ...
                }
            }
        }

+ Response 400 (application/json)

        {
            "error": 802,
            "content": {
                "succeeded": {  // [optional] 回傳成功開立的醫令之清單，若無則不用回傳
                    "orderRecordIds": {
                        "2": "K23111222222",
                        ...
                    }
                },
                "failed": [     // 未能成功開立的醫令之清單，內容為該醫令所對應之鍵值
                    "1",
                    "3",
                    ...
                ],
                "message": "ERROR DESCRIPTION"  // [string] 有關請求錯誤之描述
            }
        }


## 6/16 醫令交易檔 ID 所對應之病患醫令記錄 [/account/{accountNo}/orderRecord/{orderRecordId}{?quantity,billType,expectedExTime,confirmedTime,stage,status,sessionKey,orderRecordIds,verifier,isEmergency,specialInstruction,bedId}]

### 取得醫令記錄內容 [GET]
+ Parameters
    + sessionKey    (string) ... SessionKey

+ Response 200 (application/json)


        {
            "content": {
                "orderType": "P",                   // [string] 醫令主類別
                "orderSeqNo": "P0002",              // [string] 醫令序號 (登記排程使用)
                "hospitalCode": "HQ",               // [string] 院區碼
                "accountNo": "8ccoun7n0",           // [string] 記帳帳號
                "bedId": "b3dID",                   // [string] 床號
                "orderName": "Testing Order",       // [string] 醫令名稱
                "patientClass": "E",                // [string] 病患門住急別
                "quantity": 10,                     // [number] 數量
                "billType": "Z",                    // [string] 記帳類別，自費為 Z 健保為 E 內含為 U
                "expectedExTime": 1406938026,       // [number(timestamp)] 預計執行時間
                "confirmedTime": 1407038026,        // [number(timestamp)] 確認時間
                "creator": "111281",                // [string] 開立醫囑者員工編號
                "verifier": "111281",               // [string] 確認醫師員工編號
                "isEmergency": false,               // [boolean] 是否急做
                "stage": "一般",                     // [string] 階段
                "status": "開立",                    // [string] 狀態
                "scheduled": false,                 // [boolean] 是否已經排程
                "specialInstruction": "特殊醫囑內容",  // [string] 特殊醫囑
                "startActivateDatetime": 1435744800, // [number(timestamp), optional] 醫令有效起日 K類醫囑使用
                "endActivateDatetime": 1438423200,   // [number(timestamp), optional] 醫令有效迄日 K類醫囑使用
                "frequency": "QD",                   // [string] 頻率碼 K類醫囑使用
                "isBedside": false,                  // [boolean, optional] 是否為床邊攝影 R類醫囑使用
                "specimenCode": "sp1",               // [string] 檢體代碼 L類醫囑使用
                "questionary": [                     // [optional] 問題清單答案
                    {
                        "displayTitle": "SINGLE_SELECTION",     // [string] 問題顯示題目
                        "returnKey": "s_selection_example",     // [string] 回傳結果時該問題所對應的鍵值
                        "type": "S",                            // [string] 問題種類，如日期為 D，單選為 S
                        "required": true,                       // [boolean] 問題是否為必填項目
                        "defaultSelections": [                  // [optional] 預設或已選取項目之順序代號，當類型為 S 或 M 時使用
                            0,                                  // [number] 預設或已選取項目對應之順序代號
                            2,
                            ...
                        ],
                        "options": [                            // [optional] 選擇項目列表，當類型為 S, M 時使用
                            {
                                "displayValue": "OPTIONA: A",   // [string] 選項顯示內容
                                "returnValue": "optional_a",    // [string] 回傳時該選項所對應的值
                                "priority": 0                   // [number] 選項顯示順序
                            },
                            {
                                "displayValue": "OPTIONAL: B",  // [string] 項目顯示內容
                                "returnValue": "optiona_b",     // [string] 回傳時該選項所對應的值
                                "priority": 1                   // [number] 項目顯示順序
                            },
                            ...
                        ],
                        "freeSelectionEnable": false            // [optional, boolean] 是否允許增添選項，當類型為 S, M 時使用
                    },
                    {
                        "displayTitle": "DATE_SELECTION",       // [string] 問題顯示題目
                        "returnKey": "d_selection_example",     // [string] 回傳結果時該問題所對應的鍵值
                        "type": "D",                            // [string] 問題種類，如日期為 D，單選為 S
                        "required": true,                       // [boolean] 問題是否為必填項目
                        "dateFormat": "DD",                     // [optional, string] 當類型為 D 時使用
                        "defaultDate": 1406938026               // [optional, number(timestamp)] 預設或已經填入之答案，當類型為 D 時使用
                    },
                    {
                        "displayTitle": "INPUT_BOX",            // [string] 問題顯示題目
                        "returnKey": "input_box_example",       // [string] 回傳結果時該問題所對應的鍵值
                        "type": "T",                            // [string] 問題種類，如單行文字框為 T 多行文字框為 P
                        "required": false,                      // [boolean] 問題是否為必填項目
                        "dictionary": [                         // [optional] 常用字彙，當類型為 T 或 P 時可使用
                            "ped_1",
                            "ped_2",
                            "operation_AS1",
                            "operation_AS2",
                            ...
                        ],
                        "defaultText": "ped_1, ped_2"           // [optional, string] 預設或已經輸入之內容，當類型為 T, P 時使用
                    },
                    ...
                ]
            }
        }

### 更改醫令記錄內容 [PUT]
+ Parameters
    + orderRecordId      (string) ... 要更改記錄之 orderRecordId
    + quantity           (number) ... 數量
    + billType           (number) ... 記帳類別
    + expectedExTime     (number) ... 預計執行時間
    + confirmedTime      (number) ... 確認時間
    + verifier           (string) ... 確認醫師員工編號
    + isEmergency        (boolean) ... 是否急做
    + status             (string) ... 階段
    + stage              (string) ... 狀態
    + specialInstruction (string) ... 特殊醫囑內容
    + bedId              (string) ... 床號

+ Request ModifyOrder (application/json)

        {
            "content": {
                "hospitalCode": "HQ",                // [string] 院區碼
                "quantity": 3,                       // [number] 數量
                "billType": "E",                     // [string] 記帳類別
                "confirmedTime": 1438423200,         // [number(timestamp)] 確認時間
                "verifier": "111283",                // [string]  確認醫師員工編號
                "isEmergency": false,                // [boolean] 是否急做
                "expectedExTime": 1406938026,        // [number(timestamp)] 預計執行時間
                "specialInstruction": "Test 1",      // [string] 特殊醫囑
                "bedId": "b3dID",                    // [string] 床號
                "startActivateDatetime": 1435744800, // [number(timestamp), optional] 醫令有效起日 K類醫囑使用
                "endActivateDatetime": 1438423200,   // [number(timestamp), optional] 醫令有效迄日 K類醫囑使用
                "frequency": "QD",                   // [string] 頻率碼 K類醫囑使用
                "isBedside": false,                  // [boolean, optional] 是否為床邊攝影 R類醫囑使用
                "specimenCode": "sp1",               // [string] 檢體代碼 L類醫囑使用
                "questionary": [                     // [optional] 問答題答案，若無則不會傳入
                    {
                        "returnKey": "d_selection_example",     // [string] 問答題對應鍵值
                        "type": "S",                            // [string] 問答題類型
                        "value": [                              // [optional]
                            0,
                            1,
                            ...
                        ]
                    },
                    {
                        "returnKey": "input_box_example",       // [string] 問答題對應鍵值
                        "type": "T",                            // [string] 問答題類型
                        "value": "this is the input content"    // [optional]
                    },
                    ...
                ],
                "appendOrders": [ // [optional] 附帶醫令，若無則不會傳入
                    "TSA123001",  // [string] 醫令碼
                    "K00123110",
                    ...
                ]
            },
            "sessionKey": "E0B27FAAAE68415BA9E011E569FE4009"
        }


+ Response 200 (application/json)

        {
            "success": true
        }

+ Response 400 (application/json)

        {
            "error": 802,                                   // [number] Error Code
            "message": "THE LOCAL ERROR DESCRIPTION"        // [string] 錯誤訊息
        }
