FORMAT: 1A
HOST: http://www.wantoto.com

# DEV台大醫院行動醫療資訊系統 Web Service v1.5.0
採用 RESTful 架構規劃。所有字串編碼皆為UTF-8。

####$include{authorization}

####$include{phaseOne}

####$include{notification}

####$include{bulletin}

####$include{temp}

####$include{order_2}

####$include{medication_2}

####$include{blood}

####$include{scheduling}

####$include{media}

####$include{bed}
